### PR TITLE
make error out in not finding git@github.com:basho/riak_repl_pb_api.git

### PR DESCRIPTION
**Pull request by kellymclaughlin**
hi, when I issue make it fails at  not able to get the git@github.com:basho/riak_repl_pb_api.git

From rebar.config.script, it says the repo is under solaris_pkgname line 59
  {riak_repl_pb_api,".*",{git,"git@github.com:basho/riak_repl_pb_api.git", {tag, "0.2.2"}}}

Comment that out, build is successful. So does that repo has impact on functionality? Or it is it just unimportant?

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
I was finally able to reproduce this. PR with a fix incoming.

**Comment by jaredmorrow** [comment]
+1

**Pull request closed without merging**
