### PR TITLE
Updates for working with riak_test

### PR DESCRIPTION
**Pull request by seancribbs**
This helps support [GiddyUp](//github.com/basho/giddyup) integration and fixes a few other things. 

This PR requires the changes from basho/riak_test#335.

### CODE REVIEW

**Comment by andrewjstone** [comment]
I used the required branch of riak_test, modified my riak_test config and ran the get_object_test. Worked like a charm!
I'm going to run all the tests to ensure they work before giving the +1.

**Comment by andrewjstone** [comment]
Saw this error while running all the riak_tests, but don't think i'ts related. 18:20:43.609 [info] Wait until 'stanchion@127.0.0.1' is pingable
18:20:43.613 [error] Error in process <0.1851.0> on node 'riak_test@127.0.0.1' with exit value: {{aws_error,{socket_error,{conn_failed,{error,econnrefused}}}},[{erlcloud_s3,s3_request,9,[{file,"src/erlcloud_s3.erl"},{line,881}]},{erlcloud_s3,s3_xml_request,8,[{file,"src/erlcloud_s3.erl"},{line,814}]},{erlcloud_s3,list_buckets...

18:20:43.613 [warning] list_objects_test failed: {{aws_error,{socket_error,{conn_failed,{error,econnrefused}}}},[{erlcloud_s3,s3_request,9,[{file,"src/erlcloud_s3.erl"},{line,881}]},{erlcloud_s3,s3_xml_request,8,[{file,"src/erlcloud_s3.erl"},{line,814}]},{erlcloud_s3,list_buckets,1,[{file,"src/erlcloud_s3.erl"},{line,287}]},{list_objects_test,'-confirm/0-fun-1-',2,[{file,"riak_test/tests/list_objects_test.erl"},{line,34}]},{list_objects_test,confirm,0,[{file,"riak_test/tests/list_objects_test.erl"},{line,34}]}]}
18:20:43.615 [error]
================ list_objects_test failure stack trace =====================
{{aws_error,{socket_error,{conn_failed,{error,econnrefused}}}},
 [{erlcloud_s3,s3_request,9,[{file,"src/erlcloud_s3.erl"},{line,881}]},
  {erlcloud_s3,s3_xml_request,8,[{file,"src/erlcloud_s3.erl"},{line,814}]},
  {erlcloud_s3,list_buckets,1,[{file,"src/erlcloud_s3.erl"},{line,287}]},
  {list_objects_test,'-confirm/0-fun-1-',2,
                     [{file,"riak_test/tests/list_objects_test.erl"},
                      {line,34}]},
  {list_objects_test,confirm,0,
                     [{file,"riak_test/tests/list_objects_test.erl"},

#                       {line,34}]}]}

18:20:43.615 [notice] list_objects_test Test Run Complete

**Comment by seancribbs** [comment]
@andrewjstone I did notice that some tests were failing on my machine, but I have not yet looked into the cause. Giving it a full run tonight.

**Comment by seancribbs** [comment]
Yep, two failures:
1. [external_client_tests](https://basho-giddyup-sdc-dev.s3.amazonaws.com/15392.log)
2. [repl_test](https://basho-giddyup-sdc-dev.s3.amazonaws.com/15397.log)

I'm willing to bet the first is just something funky with my environment. I did notice, however, that waiting on stanchion to become pingable took a long time in that test.

**Comment by andrewjstone** [comment]
@seancribbs I really thought we got rid of the socket_errors as showing up in the repl_test when we replaced httpc with ibrowse in erlcloud. Guess not :( Either way, that won't hold merging up. external_client_tests also fails for me, but differently, in a way I haven't seen before. Your failures are def python environment stuff and won't hold anything up. 

Once I get the client tests to pass I'll +1 this.

**Comment by andrewjstone** [comment]
Client tests are passing. :+1: to merge once https://github.com/basho/riak_test/pull/335 is merged.

**Comment by andrewjstone** [comment]
I cleaned and rebuilt and got 12/12 on the tests :)

**Comment by seancribbs** [comment]
basho/riak_test#335 has merged, merging this.

**Pull request merged**
