### PR TITLE
Don't delete current object version on bad md5

### PR DESCRIPTION
**Pull request by reiddraper**
It [looks likes](https://github.com/basho/riak_cs/blob/bc99be0d4c62947a36cc7932f8db8173b54a4d68/src/riak_cs_put_fsm.erl#L290-L303) we delete the currently active manifest on an upload if the md5 is wrong, instead of just never putting this one into the active state.

### CODE REVIEW

**Comment by reiddraper** [comment]
Confirmed this is an issue. Due to some other code organization, it might be easier now to simply leave the manifest in the writing state, rather than pro-actively garbage-collect it. I'm continuing to investigate.

**Comment by reiddraper** [comment]
What do you all think about getting this in 1.4.3?

**Comment by kellymclaughlin** [comment]
- [x] Eunit and eqc tests pass
- [x] Pulse tests pass
- [x] Client tests pass
- [x] Int tests pass
- [x] riak_test tests pass

**Comment by kellymclaughlin** [comment]
Verified the additional python test fails with current `release/1.4` code and passes with this change.

**Comment by reiddraper** [comment]
> Verified the additional python test fails with current release/1.4 code and passes with this change.

Marginally related, any thoughts on pros/cons of having a bugfix and the accompanying test in the same commit, or doing two commits?

**Comment by kellymclaughlin** [comment]
> Marginally related, any thoughts on pros/cons of having a bugfix and the accompanying test in the same commit, or doing two commits?

I think it's fine since they are very much related. The only thing I would consider is amending the commit message to mention the addition of the test. Other than that I have no problem with it.

**Comment by kellymclaughlin** [comment]
Looks good! +1 to merge.

**Pull request merged**
