### PR TITLE
Refer forked xmerl to avoid many undef exceptions thrown

### PR DESCRIPTION
**Pull request by shino**
Original issue: #669 

Add forked xmerl to deps which refers https://github.com/shino/xmerl/pull/2 .
Xmerl source is based on Kelly's fork, updated to R16B02's and fetched the following change.
- Pull request to erlang/otp by Richard Carlsson: https://github.com/erlang/otp/pull/87

The PR was already merged to both maint and master.
Once new Erlang/OTP will be released (probably R16B03), we don't need forked one any more.

### CODE REVIEW

**Comment by shino** [comment]
https://github.com/erlang/otp/pull/78 was closed in favor of https://github.com/erlang/otp/pull/87 .
(https://github.com/erlang/otp/pull/87 is not yet merged)

The xmerl fork should be based on https://github.com/erlang/otp/pull/87.

**Comment by kellymclaughlin** [comment]
@shino Do you want to pull the change from [erlang/otp#87](https://github.com/erlang/otp/pull/87) into your fork or I can pull it into mine. Just a guess, but it seems unlikely that the fix is going to be part of an OTP release until R17. I'd vote we go ahead and merge the change to use the fork in the interim.

**Comment by shino** [comment]
@kellymclaughlin I will do. Sorry that my comment was not apparent.

**Comment by shino** [comment]
Ready for review again.
- Force pushed to chage xmerl's fork branch
- Update the description (comment at top)

**Comment by shino** [comment]
R16B03 has been released and this bug is fixed.
http://www.erlang.org/download/otp_src_R16B03.readme

If we use R16B03 in packaging, this PR should be closed _without_ merge.

**Comment by kuenishi** [comment]
I think we have to change `rebar.config` to force using R16B03 (not former ones) before closing or am I caremad?

**Comment by reiddraper** [comment]
> I think we have to change rebar.config to force using R16B03 (not former ones) before closing or am I caremad?

Let's leave this open until it's actually resolved.

**Comment by reiddraper** [comment]
I rebased this pull-request to try and test it, and am getting this error from dialyzer:

```
==> riak_cs (dialyzer)

dialyzer: Could not merge PLTs since they are not disjoint
The following files are included in more than one PLTs:
["xmerl.beam","xmerl_b64Bin.beam","xmerl_b64Bin_scan.beam",
 "xmerl_eventp.beam","xmerl_html.beam","xmerl_lib.beam","xmerl_otpsgml.beam",
 "xmerl_regexp.beam","xmerl_sax_old_dom.beam","xmerl_sax_parser.beam",
 "xmerl_sax_parser_latin1.beam","xmerl_sax_parser_list.beam",
 "xmerl_sax_parser_utf16be.beam","xmerl_sax_parser_utf16le.beam",
 "xmerl_sax_parser_utf8.beam","xmerl_sax_simple_dom.beam","xmerl_scan.beam",
 "xmerl_sgml.beam","xmerl_simple.beam","xmerl_text.beam","xmerl_ucs.beam",
 "xmerl_uri.beam","xmerl_validate.beam","xmerl_xlate.beam","xmerl_xml.beam",
 "xmerl_xpath.beam","xmerl_xpath_lib.beam","xmerl_xpath_parse.beam",
 "xmerl_xpath_pred.beam","xmerl_xpath_scan.beam","xmerl_xs.beam",
 "xmerl_xsd.beam","xmerl_xsd_type.beam"]

make: *** [dialyzer] Error 1
```

**Comment by reiddraper** [comment]
Ah nice, I've fixed this by removing `xmerl` from `DIALYZER_APPS` in the top-level Makefile. @shino, do you mind if I force-push some commits to this branch?

**Comment by reiddraper** [comment]
Instead of force-pushing, I just created #848. Closing.

**Comment by shino** [comment]
Thanks for the fix! :smile:

**Pull request closed without merging**
