### PR TITLE
Serialize user updates through stanchion

### PR DESCRIPTION
**Pull request by kellymclaughlin**

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
This PR relies on [this](https://github.com/basho/stanchion/pull/53) stanchion PR and [this](https://github.com/basho/velvet/pull/8) velvet PR.

**Comment by reiddraper** [comment]
I'm seeing 4 boto client-test failures:
- test_get_bucket_acl
- test_get_object_acl
- test_set_bucket_acl
- test_set_object_acl

**Comment by kellymclaughlin** [comment]
Resolved those test failures with [e96115d](https://github.com/basho/stanchion/commit/e96115d734ada79bb6aa30edc9930f21fdc3ea28) to the stanchion `feature/user-updates` branch.

**Comment by reiddraper** [comment]
- [x] Eunit and eqc tests pass
- [x] Pulse tests
- [x] Client and int tests pass
- [x] Dialyzer output clean
- [x] `riak_test` tests pass

**Comment by reiddraper** [comment]
A couple of dialyzer warnings, but nothing related to these changes.

**Comment by reiddraper** [comment]
Seeing a failure with the `user_test`:

```
{{assertEqual_failed,[{module,user_test},
                      {line,112},
                      {expression,"ErrorResult"},
                      {expected,"UserAlreadyExists"},
                      {value,"BadRequest"}]},
```

**Comment by reiddraper** [comment]
The above error was me not using the new stanchion PR with rt.

**Comment by reiddraper** [comment]
+1 to merge

**Pull request closed without merging**
