### PR TITLE
Put to a non-existent bucket -> HTTP 500 error 

### PR DESCRIPTION
**Pull request by kuenishi**
s3cmd put ~/foo s3://testbotoXX/foo where the S3 bucket `testbotoXX` does not exist:

```
15:12:21.878 [error] webmachine error: path="/buckets/testbotoXX/objects/foo"
{error,{case_clause,{error,notfound}},[{riak_cs_wm_utils,translate_bucket_policy,3,[{file,"src/riak_cs_wm_utils.erl"},{line,596}]},{riak_cs_wm_utils,object_access_authorize_helper,4,[{file,"src/riak_cs_wm_utils.erl"},{line,520}]},{riak_cs_wm_common,authorize,2,[{file,"src/riak_cs_wm_common.erl"},{line,309}]},{riak_cs_wm_common,forbidden,2,[{file,"src/riak_cs_wm_common.erl"},{line,147}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,183}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,141}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,212}]}]}
```

### CODE REVIEW

**Comment by reiddraper** [comment]
Just confirmed this should return 404:

```
s3cmd --debug -c ~/.s3cfg.real-s3-personal-account put rebar.config s3://nowaythisisrealyodognono
```

shows:

`ERROR: S3 error: 404 (NoSuchBucket): The specified bucket does not exist`

**Comment by reiddraper** [comment]
I still get this error:

```
(riak-cs@127.0.0.1)1> 13:35:46.891 [error] webmachine error: path="/buckets/noway/objects/rebar.config"
{error,{case_clause,{error,no_such_bucket}},[{riak_cs_wm_utils,translate_bucket_policy,3,[{file,"src/riak_cs_wm_utils.erl"},{line,596}]},{riak_cs_wm_utils,object_access_authorize_helper,4,[{file,"src/riak_cs_wm_utils.erl"},{line,520}]},{riak_cs_wm_common,authorize,2,[{file,"src/riak_cs_wm_common.erl"},{line,309}]},{riak_cs_wm_common,forbidden,2,[{file,"src/riak_cs_wm_common.erl"},{line,147}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,183}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,141}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,212}]}]}
[{riak_cs_wm_utils,translate_bucket_policy,3,[{file,"src/riak_cs_wm_utils.erl"},{line,596}]},{riak_cs_wm_utils,object_access_authorize_helper,4,[{file,"src/riak_cs_wm_utils.erl"},{line,520}]},{riak_cs_wm_common,authorize,2,[{file,"src/riak_cs_wm_common.erl"},{line,309}]},{riak_cs_wm_common,forbidden,2,[{file,"src/riak_cs_wm_common.erl"},{line,147}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,183}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,141}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,212}]}]
```

**Comment by reiddraper** [comment]
We should add a regression test for this as well.

**Comment by kuenishi** [comment]
Sorry, I thought I had fixed it and I had tested it :(
Is riak_test the best place to add regression? I'm still failing running it, so I'll try it tomorrow.

**Comment by kellymclaughlin** [comment]
I know @kota is very busy and I had a few minutes so I went ahead and made a new [pull request](https://github.com/basho/riak_cs/pull/442) with a fix and a regression suite that is targeted against the `release/1.3` branch.

**Comment by kuenishi** [comment]
@kellymclaughlin ok, closing this issue to avoid duplication

**Pull request closed without merging**
