### PR TITLE
Fetching own user info fails if the key_id is not specified.

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Marcel reported that doing s3cmd get s3://riak-cs/user returns the error: "Failed to fetch user record. KeyId: []" instead of the user information.

### CODE REVIEW

**Comment by slfritchie** [comment]
Howdy.  Sorry, I'm a bit puzzled here.  I see the same behavior on today's master branch and this PR's feature branch.

```
# master
% s3cmd -f get s3://riak-cs/user
s3://riak-cs/user -> ./user  [1 of 1]
ERROR: S3 error: 403 (Forbidden): 

# feature branch
% s3cmd -f get s3://riak-cs/user
s3://riak-cs/user -> ./user  [1 of 1]
ERROR: S3 error: 403 (Forbidden): 
```

**Comment by kellymclaughlin** [comment]
That's strange. I just tested again and it works for me. Would you mind trying once more?

```
s3cmd -f -c ~/.s3cfg-moss get s3://riak-cs/user -
s3://riak-cs/user -> <stdout>  [1 of 1]
 325 of 325   100% in    0s    31.81 kB/s  doneail>test2@test.com</Email><DisplayName>test2</DisplayName><Name>test2</Name><KeyId>NMYM2PXTW2OIJQN_ZKWF</KeyId><KeySecret>JzYAZFE_HLA9ZLmAOgycpPCJRvSitvnoDUe7-g==</KeySecret><Id>7f3747cdc0e9dc9df242ba797caf598ca8910dce3f76e5e93d320da8b668db8c</Id><Status>enabled</Status></User>
```

**Comment by slfritchie** [comment]
Kelly, I still get a 403 forbidden.  I had provisioned a new user, just in case there was something bogus lying around in whatever user record I'd been using in the past.  Then I used that new user to verify that I couldn't create a bucket that already existed but could create a new bucket.

```
% s3cmd mb s3://test
ERROR: Bucket 'test' already exists

% s3cmd mb s3://test2
Bucket 's3://test2/' created
```

But then this doesn't work as expected:

```
% s3cmd -f get s3://riak-cs/user -
s3://riak-cs/user -> <stdout>  [1 of 1]
ERROR: S3 error: 403 (Forbidden): 
```

My version of riak_moss:

```
% git branch | egrep '\*'
* moss254-user-info-request

% git log | head
commit 6cd86b0c2dcf85dc89502a5c067725ed33ea22be
Author: Kelly McLaughlin <kelly@basho.com>
Date:   Wed Jul 25 14:12:37 2012 -0600

    Allow user to list their account info without specifying their key_id.

    Fixes MOSS254

    Fix a regression that prevented users from requesting their user
    account information without specifying the key_id.
```

**Comment by slfritchie** [comment]
Pilot error on my part: `rm -rf deps ; make && make stage` allows the feature branch to work as expected.  The master branch gives HTTP 403 Forbidden code (not quite sure where the "Failed to fetch..." message comes from.  +1 to merge, sorry about the delay.

**Pull request merged**
