### PR TITLE
Add prefix_multi option for riak kv backend [JIRA: RCS-268]

### PR DESCRIPTION
**Pull request by shino**
Cf. Introduce `riak_kv_multi_prefix_backend` by kuenishi · Pull Request #1082 (RCS-130)
    https://github.com/basho/riak_kv/pull/1082

### CODE REVIEW

**Comment by shino** [comment]
Still WIP because now I'm executing r_t

**Comment by shino** [comment]
All r_t passed. Ready for review.

**Comment by shino** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_cs/pull/1220/files

no need to be mentioned in release note, only test code change. 

**_[posted via JIRA by Shunichi Shinohara]**_

**Pull request merged**
