### PR TITLE
Expand User API to be able to issue new credentials to a user

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Changes to allow users to change generate a new `key_secret` for their account.  Return updated user document in the response body. Also allow admin users to generate a new `key_secret` for a specified user account.
## Testing

The `key_secret` for a user account can be reissued by a `PUT` to `/riak-cs/user` with the appropriate JSON or XML document. For admin users the `PUT` would be to `/riak-cs/user/<key-id>`. The documents should look as follows:

JSON

```
{"new_key_secret":true}
```

XML

```
<?xml version="1.0" encoding="UTF-8"?>
<UserUpdate>
  <NewKeySecret>true</NewKeySecret>
</UserUpdate>
```

**NOTE** The `new_key_secret` field may be combined with other user update fields in the same request. Currently, the only other supported field is `status`, but more may be added in the future. Unsupported fields are simply ignored.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@kellymclaughlin I'm running into issues when creating users on this branch.  However, retrieving a user by key_id is working fine.

```
      Expected([201]) <=> Actual(403 Forbidden)
        request => {:connect_timeout=>60, :headers=>{"Content-Type"=>"application/json", "Host"=>"localhost:8080", "Content-Length"=>55}, :instrumentor_name=>"excon", :mock=>false, :read_timeout=>60, :retry_limit=>4, :ssl_ca_file=>"/Users/cmeiklejohn/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.13.4/data/cacert.pem", :ssl_verify_peer=>true, :write_timeout=>60, :host=>"localhost", :path=>"/user", :port=>"8080", :query=>nil, :scheme=>"http", :expects=>[201], :method=>"POST", :body=>"{\"email\":\"user-1339816031-4@example.com\",\"name\":\"User\"}"}
```

**Comment by cmeiklejohn** [comment]
Confirmed switching back to master resolves the problem.

**Comment by kellymclaughlin** [comment]
Hmm, don't know that I tried creating a user on that branch. I'll check it out and see if I have similar issues.

**Comment by cmeiklejohn** [comment]
thanks @kellymclaughlin

**Comment by kellymclaughlin** [comment]
@cmeiklejohn Oh yes, I forgot to mention that I based this branch on the changes to restrict user creation. Checkout [this](https://github.com/basho/riak_moss/pull/211) pull request for more details. You can either create a user using the admin creds by default of set `anonymous_user_creation` to `true`.

**Comment by cmeiklejohn** [comment]
@kellymclaughlin see comment on other pull request.

**Comment by cmeiklejohn** [comment]
+1, added support to fog as well.

**Comment by cmeiklejohn** [comment]
+1 revisions

**Pull request closed without merging**
