### PR TITLE
fix request pool size on riak_test

### PR DESCRIPTION
**Pull request by kuenishi**
stats_test has been failing due to the change of default pool size.

### CODE REVIEW

**Comment by kuenishi** [comment]
oh no, this was just for my branch.

**Comment by kuenishi** [comment]
Better way.

**Comment by shino** [comment]
@kuenishi this PR should go to target branch instead of develop?

**Comment by kuenishi** [comment]
@shino Both is okay, but to avoid bad merge conflict we'd better use either of them. I think develop and release/1.5 should have same diff set until 1.5.0 release. So, for now let's use develop.

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
