### PR TITLE
Add exponential back off with randomization to avoid sibling explosion

### PR DESCRIPTION
**Pull request by shino**
Addresses #882 (together with #915).

When multipart uploads are executed in concurrent, get-modify-put manifest objects
may be interleaved and lead to sibling explosion.
This PR add retries with sleep to releive it.

Three knobs are introduced.
- `manifest_update_max_retries` (default: 4)
  
  Max number of reties for GET manifests before update.
- `manifest_siblings_suppress` (default: 5)
  
  The threshold for the number of manifest object siblings to trigger suppression logic.
  If the number of siblings is equal to or greater than this value,
  retry logic is applied.
- `manifest_siblings_force_update_at_last_retry` (default: 15)
  
  The threshold for the number of manifest object siblings to
  force update at the last retry.
  If the number of siblings is less than this value,
  update without gamble (see below) at the last retry.
### Logic

After getting manifest object, check the number of siblings.
If it is less than `manifest_siblings_suppress`,
modify/put it without sleep or retry.
Otherwise, do a simple gamble.
- First, generate random uniform integer from 0 to 9.
- If it is 0, then win! update modify/put manifests.
- Other than that, sleep and retry from getting manifest object.

This randomness is necessary because there should be a chance to
resolve siblings which needs modify/put.

Also, at the last retry attempt, depending on the #(siblings),
the upload forcedly move to upload without gambling.

Another randomness is in sleep intervals.
Sleep intervals are uniformly distributed in the ranges 0.5 +/- 0.25, 1 +/- 0.5,
2 +/- 1, 4 +/- 2, for 1st retry, 2nd, 3rd,... respectively.
### Misc notes
- No dependency on the number of siblings other than threashold for suppression.
  If the current logic not enough, some penalty for sleep interval for large
  number of siblings might help (or not. I don't know).
- Add `manifest_update_retry_sleep` to riak_cs_stats.
  It collects sleep intervals as latency (a bit of abuse).

### CODE REVIEW

**Comment by kuenishi** [comment]
Maybe #679 is related

**Comment by shino** [comment]
Current status of the branch
- rebased on release/1.5 after 1.5.0 release
- remove warning log because it was already added at 1.5.0
- isolate async update error handling (not yet completed), which should be addressed another issue. related to #920 

TODOs
- Increase sleep interval for "far" beyond threshold (e.g. > 2*threshold)
- Add the way to monitor retry by threshold (warning log is too noisy, probably).

**Comment by kuenishi** [comment]
With this code, when # of siblings is more than threshold and there're less than 10 concurrent uploads, there happens unnecessary wait. Then the max retry is 5, so if there are a few concurrent uploads, there will be unnecessary wait and re-getting from Riak. If Riak object larger, the read load will get heavier. Andalso, there is non-trivial possibility to fail for all 5 retries. Its probability is `0.9^5 = 0.590..`

So I would suggest not to throw a dice when `MaxRetries == Retries` which is the last chance.

**Comment by shino** [comment]
> Its probability is 0.9^5 = 0.590..

This is the probability in case all the concurrent uploads fails to resolve siblings.
If one upload can resolve siblings, then other uploads after retry does not see siblings over threshold.

My estimation is
- thresold=5 then there are 5+ uploads
- each uploads retry up to 5 times, them 25+ trials
- 1/10 winning percentage is not so bad to bet

But... more consideration needed (for me)

**Comment by kuenishi** [comment]
Well, then we need discussion on whether `0.9^25 = 0.0717...` is low enough for that. Let's spill water in tern.

**Comment by shino** [comment]
Update description to reflect the last commit 3f51452

**Comment by shino** [comment]
Close this.
Retries in overloaded situation seems bad.  Prefer simple sleep at #959 .

**Pull request closed without merging**
