### PR TITLE
Add release note on #855 fix

### PR DESCRIPTION
**Pull request by kuenishi**

### CODE REVIEW

**Comment by shino** [comment]
Sorry that I forgot to add #876 . Could you please add it?

**Comment by shino** [comment]
> Also, all CS nodes which don't run GC should be upgraded before CS
>   node which does run GC upgraded to let leeway second system work
>   properly.

Is it danger that GC-enabled node has old version?
DELETEd objects may be collected just after deletion.

```
                    DELETE object
  CS w/o GC --------X--------------
  (1.5.x)           |
                    |
                    V
  riak-cs-gc  ----------------------
                       ^
                       |
                       |
  CS w/ GC  -----------O-----------
  (1.4.x)              GC triggered
```

When GC-enabled node is new version, it is safer.

```
                    DELETE object
  CS w/o GC --------X--------------
  (1.4.x)           |
                    +--------+
                             V
  riak-cs-gc  ----------------------
               ^
               +-------+
                       |
  CS w/ GC  -----------O-----------
  (1.5.x)              GC triggered
```

**Comment by shino** [comment]
Thanks for adding the line :smile: 
Diff looks nice.

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
