### PR TITLE
1.4 release notes

### PR DESCRIPTION
**Pull request by reiddraper**
This is just a first stab, not ready to merge. Please edit as needed.

### CODE REVIEW

**Comment by kuenishi** [comment]
Is this https://github.com/basho/webmachine/pull/158 included in this release, as latest webmachine? This gained the performance a lot. I think it's worth mentioning, or not because we don't have precise benchmark.

**Comment by reiddraper** [comment]
Looks like it's in the 1.10.3 tag. We're using 1.10.2. We can definitely try and update the rebar.config before releasing as part of our testing.

**Comment by kellymclaughlin** [comment]
+1 to planning to use the 1.10.3 webmachine tag for the release.

**Comment by reiddraper** [comment]
Update PR in #637.

**Comment by kellymclaughlin** [comment]
:+1:

**Pull request merged**
