### PR TITLE
Remove name reference to access archiver processes

### PR DESCRIPTION
**Pull request by shino**
Original issue: #746

To complete multiple archiver processes support introduced at:
  #717 Only a single access archiver can run at a time
  https://github.com/basho/riak_cs/pull/717
registered name references should be removed.

### CODE REVIEW

**Comment by ksauzz** [comment]
The patch works fine. :+1: from me.

get empty usage before flushing.

```
kazuhiro@squirrel☁ /usr/local/src/riak_cs 2.0.0-p195 [b0f8977] ⚡
% s3cmd -c user.cfg -q get s3://riak-cs/usage/BJL6GJVPTXMTNI_O27WK/a/20131128T090600Z/20131130T010000Z -f && jsonpp 20131130T010000Z
{
  "Access": {
    "Nodes": [],
    "Errors": []
  },
  "Storage": "not_requested"
}
```

flush access samples with access archiver

```
kazuhiro@squirrel☁ /usr/local/src/riak_cs 2.0.0-p195 [b0f8977] ⚡
% rel/riak-cs/bin/riak-cs-access flush
Adding current log to archive queue...
Waiting for archiver to finish...
Currently archiving 20131128T090529Z-20131128T090922Z
0 more archives to flush
All access logs were flushed.

```

get a stored usage

```
kazuhiro@squirrel☁ /usr/local/src/riak_cs 2.0.0-p195 [b0f8977] ⚡
% s3cmd -c user.cfg -q get s3://riak-cs/usage/BJL6GJVPTXMTNI_O27WK/a/20131128T090600Z/20131130T010000Z -f && jsonpp 20131130T010000Z
{
  "Access": {
    "Nodes": [
      {
        "Node": "riak-cs@127.0.0.1",
        "Samples": [
          {
            "StartTime": "20131128T090529Z",
            "EndTime": "20131128T090922Z",
            "UsageRead": {
              "BytesOut": 1193,
              "Count": 8
            }
          }
        ]
      }
    ],
    "Errors": []
  },
  "Storage": "not_requested"
}

```

**Comment by shino** [comment]
@ksauzz Thanks!

Wait another +1 with source code review.

**Comment by reiddraper** [comment]
Oops, yeah, looks like I broke this in #717 :(

**Comment by shino** [comment]
Added riak_test module for access stats.
Ready for review.

**Comment by reiddraper** [comment]
I'm hoping to review soon, but have been having issues with my install since upgrading to Mavericks. I'll get this reviewed once I get that straightened out.

**Comment by kuenishi** [comment]
The code looks nice, I'm giving my +1, if @reiddraper is still busy.

**Comment by shino** [comment]
:christmas_tree:

**Pull request merged**
