### PR TITLE
Automated code formatting [includes RFC]

### PR DESCRIPTION
**Pull request by kuenishi**
Inspired by `go fmt` and triggered by the discussion in https://github.com/basho/riak_kv/pull/822 , I hit on a way of automated Erlang code formatting. This just applies `(erlang-indent-region)` and `(delete-trailing-whitespaces)` to _ALL_ files included in the repository.

The points of discussions will be:
1. Is the autoprocesses formatting good? - The results are included in This PR.
2. Is the automatic indentation enough to do strict formatting?
3. Is the emacs lisp code valid? - where to find `erlang-start.el` ?

At my first trial to riak_cs repository, there were a lot of good re-formatting.
Give me your thoughts.

Current way to hack this, just type `make fmt` with your emacs and `erlang-mode` ready at `"/usr/local/erlang/R16B03/lib/erlang/lib/tools-2.6.13/emacs/"` .

### CODE REVIEW

**Comment by reiddraper** [comment]
I'm not an emacs user, so I'm likely missing many (all?) of the prerequisites. I have an emacs installed, but haven't done anything else. Is there a set of minimal instructions to get the dependencies up?

``` shell
➜  riak_cs git:(feature/erlfmt) make fmt
emacs --script priv/erlfmt.el src/*.erl
Cannot open load file: erlang-start
make: *** [fmt] Error 255
```

**Comment by kuenishi** [comment]
My intention of this PR was almost an RFC with very primitive, test implementation and I forgot to mention it (sorry).  
The script currently assumes R16B03 installed with `--prefix=/usr/local/erlang/R16B03` . I'll update the script to find `erl` command and search erlang-start.el files.

**Comment by reiddraper** [comment]
Cool. I like the idea, for sure.

**Comment by kuenishi** [comment]
Updated. Now anyone who has emacs and erlang installed can try this.

Several other my trials:
- I tried `erl_tidy` included in OTP. It was not so good as it doesn't format type/specs cleanly.
- I googled and found [wrangler](https://github.com/RefactoringTools/Wrangler), but its focus is a little bit different from what I want.

**Comment by kuenishi** [comment]
TODO: try `(erlang-font-lock-level-2)` after find-file . for here: https://github.com/basho/riak_cs/pull/808#discussion-diff-9736682R116

**Pull request closed without merging**
