### PR TITLE
rebar config script to isolate ee deps

### PR DESCRIPTION
**Pull request by kellymclaughlin**

### CODE REVIEW

**Comment by jaredmorrow** [comment]
+1

**Comment by jaredmorrow** [comment]
Added to CI, here's output confirming the change http://buildbot.bos1/builders/riak-cs-ee-build-ubuntu-1204-64/builds/0/steps/shell_1/logs/stdio

**Comment by jaredmorrow** [comment]
We will need something else for the packages, because right now all the "ee" packages will still be named riak-cs, and I assume we'd want them riak-cs-ee?  We can possibly modify the pkg.vars.config with the rebar.config.script.

**Comment by kellymclaughlin** [comment]
I've started working on a hack to the `rebar.config.script` to write to `pkg.var.config`, but it looks like the name of the package ultimately comes from `PKG_ID` in `Makefile`. Can you verify this?

**Comment by jaredmorrow** [comment]
PKG_ID names the tarball that tars up the `rel` directory initially, but ultimately the `package_name` names the package.  If we just modify the `package_name` to `riak-cs-ee` or something that will work.  I tested my theory on OSX and Ubuntu to be sure.

Below is the package metadata from my test ubuntu package:

```
buildbot@build-ubuntu-1204-64:~/dev/riak_cs/package/packages$ dpkg-deb -I riak-cs-ee_1.3.0rc1.19.geacef4e-1_amd64.deb  new debian package, version 2.0.
 size 22404350 bytes: control archive= 1287 bytes.
     108 bytes,     5 lines      conffiles
     348 bytes,    11 lines      control
    1074 bytes,    54 lines   *  postinst             #!/bin/sh
    1714 bytes,    66 lines   *  postrm               #!/bin/sh
 Package: riak-cs-ee
 Version: 1.3.0rc1.19.geacef4e-1
 Architecture: amd64
 Maintainer: Basho Package Maintainer <packaging@basho.com>
 Installed-Size: 32914
 Depends: libc6 (>= 2.15), libssl1.0.0 (>= 1.0.0), libtinfo5, adduser, logrotate, sudo
 Section: net
 Priority: extra
 Homepage: http://basho.com
 Description: Riak Cloud Storage
   Riak Cloud Storage
```

**Comment by kellymclaughlin** [comment]
Ok I'll test that and push that up. Should the entry for license in
pkg.vars.config also be updated?

**Comment by jaredmorrow** [comment]
Yes I suppose the licenses are different now.

**Comment by kellymclaughlin** [comment]
I am not seeing `package_name` have an effect when running `make package` on OSX. 

```
11:31:06:riak_cs(bugfix/rebar-config-script *) $ ls package/packages/
riak-cs-1.3.0rc1.19.ga505f98-OSX-x86_64.tar.gz     riak-cs-1.3.0rc1.19.ga505f98-OSX-x86_64.tar.gz.sha
```

The `pkg.vars.config` looks like this:

```
{package_name, "riak-cs-ee"}.
{package_install_name, "riak-cs"}.
{package_install_user, "riakcs"}.
{package_install_group, "riak"}.
{package_install_user_desc, "Riak CS user"}.
{package_commands, {list, [[{name, "riak-cs"}], [{name, "riak-cs-access"}], [{name, "riak-cs-gc"}], [{name, "riak-cs-storage"}]]}}.
{package_shortdesc, "Riak CS"}.
{package_patch_dir, "basho-patches"}.
{package_desc, "Riak CS"}.
{bin_or_sbin, "sbin"}.
{license_type, "Proprietary"}.
{copyright, "2013 Basho Technologies, Inc"}.
{vendor_name, "Basho Technologies, Inc"}.
{vendor_url, "http://basho.com"}.
{vendor_contact_name, "Basho Package Maintainer"}.
{vendor_contact_email, "packaging@basho.com"}.
{license_full_text, "This software is provided under license from Basho Technologies."}.
'{solaris_pkgname, "BASHOriak-cs"}.
```

**Comment by jaredmorrow** [comment]
But did you commit that change?  Not push, just commit. Make package takes a clean checkout of the repo.  So with that in mind, rewriting the pkg.vars.config probably will not work. Might just have build EE from a new tag.

**Comment by kellymclaughlin** [comment]
Ok after committing the change to `rebar.config.script` it seems to work well. This seems like it will work ok. I took the path of least resistance and just plopped the raw contents of `pkg.vars.confg` into `rebar.config.script`. It could be done nicer, but this gets the job done. Is there something I am overlooking that may prevent this approach from working for us?

**Comment by jaredmorrow** [comment]
Nope, I guess the rebar.config.script gets run after the new clone during the package step, so everything is fine.  I just ran a test build and most of the packages built.  There were a couple that used `package_name` and `PKG_ID` in the wrong spot, but I'll fix that in `node_package` and push a new tag.   I'm +1 on this now.

Thanks @kellymclaughlin

**Comment by jaredmorrow** [comment]
To avoid confusion, the `pkg.vars.config` file should be deleted so it is obvious it is written by the `rebar.config.script`

**Comment by kellymclaughlin** [comment]
Ok I removed the default `pkg.vars.config` file and added it to `.gitignore`. I squashed it all down to a single commit so I'll let you give a final +1 before merging it in.

**Comment by jaredmorrow** [comment]
Let me fix the two node_package errors tonight and add and updated node_package tag to this PR to make it a proper never-broken PR to the release.

**Comment by jaredmorrow** [comment]
With the `node_package` update the package now all build correctly.  +1

**Pull request merged**
