### PR TITLE
Update Release Notes for 2.0.1

### PR DESCRIPTION
**Pull request by lrnrthr**

### CODE REVIEW

**Comment by lrnrthr** [comment]
This file should take the place of the RELEASE-NOTES.md file.

**Comment by kuenishi** [comment]
Thank you for grammar correction, but I don't understand why we're changing item listing style at version update from 2.0.0 to 2.0.1. I'd love unified style in a single text file.

**Comment by lrnrthr** [comment]
@kuenishi I changed the item listing style because I was asked to create a standard style for release notes across Basho. However, your comment has made me think that it may be best to do so at 2.1 rather than 2.0.1. I will update my PR.

**Comment by kuenishi** [comment]
@laurenrother that makes sense.

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
