### PR TITLE
bucket policy: use binary_to_existing_atom/2 instead of binary_to_atom/2

### PR DESCRIPTION
**Pull request by kuenishi**
```
use binary_to_existing_atom/2 to protect atom table.
but no other good place to register atoms into atom tables
defined in ?SUPPORTED_BUCKET_ACTION and ?SUPPORTED_OBJECT_ACTION
```

https://github.com/basho/riak_cs/blob/master/src/riak_cs_s3_policy.erl#L448

### CODE REVIEW

**Comment by kuenishi** [comment]
I found no problem occurs here. Maybe it was because it was some mistake when filing this issue.

**Comment by shino** [comment]
policy works fine.

Error happened in usage xml output .

Command:

```
s3curl.pl --id local_rcs -- -s -v -x localhost:8080 -H 'Accept: application/xml' 'http://usage.s3.amazonaws.com/J8YOE0YCQYB9HRONBYXC/a/20130212T000000Z/20130213T000000Z'
```

Error in console:

```
17:08:05.598 [error] webmachine error: path="/usage/J8YOE0YCQYB9HRONBYXC/a/20130212T000000Z/20130213T000000Z"
[{webmachine_util,escape_quotes,[{error,{error,badarg,[{erlang,binary_to_existing_atom,[<<"StartTime">>,latin1],[]},{riak_cs_wm_usage,xml_name,1,[{file,"src/riak_cs_wm_usage.erl"},{line,342}]},{riak_cs_wm_usage,xml_sample,3,[{file,"src/riak_cs_wm_usage.erl"},{line,324}]},{riak_cs_wm_usage,'-xml_access/1-lc$^1/1-1-',1,[{file,"src/riak_cs_wm_usage.erl"},{line,311}]},{riak_cs_wm_usage,'-xml_access/1-lc$^0/1-0-',1,[{file,"src/riak_cs_wm_usage.erl"},{line,311}]},{riak_cs_wm_usage,xml_access,1,[{file,"src/riak_cs_wm_usage.erl"},{line,310}]},{riak_cs_wm_usage,produce_xml,2,[{file,"src/riak_cs_wm_usage.erl"},{line,295}]},{riak_cs_wm_usage,generate_etag,2,[{file,"src/riak_cs_wm_usage.erl"},{line,210}]}]}},"\""],[{file,"src/webmachine_util.erl"},{line,330}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,527}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,33}]},{webmachine_mochiweb,loop,1,[{file,"src/webmachine_mochiweb.erl"},{line,66}]},{mochiweb_http,parse_headers,5,[{file,"src/mochiweb_http.erl"},{line,180}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]
```

Probably the tag name "StartTime" can not be converted to atom.

**Comment by kuenishi** [comment]
https://github.com/basho/riak_cs/blob/master/src/riak_cs_access_log_handler.erl#L289

**Comment by shino** [comment]
It works.

One tiny point, some TAB characters in on_load function.

After untabify it, +1 to merge.

**Comment by kuenishi** [comment]
Removed hard tab. poor Debian default emacs - fixed and rebased.

**Pull request merged**
