### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kuenishi**
TODO: update eper

### CODE REVIEW

**Comment by kuenishi** [comment]
~~https://github.com/basho/velvet/pull/19 This is another dep.~~

**Comment by kuenishi** [comment]
And this: https://github.com/basho/riak_cs_multibag/pull/27

**Comment by kuenishi** [comment]
...and maybe this one: https://github.com/basho/eper/tree/ku-fresh-upstream-0.92

**Comment by kuenishi** [comment]
Please review #1197 prior to this.

**Comment by kuenishi** [comment]
Updated ＼(^o^)／

**Comment by shino** [comment]
All r_t passed :confetti_ball:

**Comment by shino** [comment]
@borshop merge

**Comment by kuenishi** [comment]
For release note:

Update cuttlefish to 2.0.4, node_package to 2.0.3, riak-erlang-client to 2.1.1, lager to 2.1.1, lager_syslog to 2.1.1, eper to 0.92 (Basho patched),  cluster_info to 2.0.3, riak_repl_pb_api to 2.1.1 and riak_cs_multibag to 2.1.0.

**Comment by Basho-JIRA** [comment]
For release note:

Update cuttlefish to 2.0.4, node_package to 2.0.3, riak-erlang-client to 2.1.1, lager to 2.1.1, lager_syslog to 2.1.1, eper to 0.92 (Basho patched), cluster_info to 2.0.3, riak_repl_pb_api to 2.1.1 and riak_cs_multibag to 2.1.0.

**_[posted via JIRA by Kota Uenishi]**_

**Pull request merged**
