### PR TITLE
generate proper dev/devN/sbin/riak-cs (empty RUNNER_BASE_DIR breaks the ...

### PR DESCRIPTION
**Pull request by kuenishi**
...script)

### CODE REVIEW

**Comment by bookshelfdave** [comment]
@kuenishi can you wait to merge this until the newest build of CS is released? riak_test was just integrated, and it depends on the devrel targets.

**Comment by kuenishi** [comment]
@metadave I see. Sorry I don't know so much about riak_test, so I'll be glad if there's any problem merging this patch.

**Comment by jaredmorrow** [comment]
This problem should now be fixed from PR 290 merged to master.

**Comment by kuenishi** [comment]
thanx!

**Pull request closed without merging**
