### PR TITLE
Set relative paths for vars settings to fix rel/devrel

### PR DESCRIPTION
**Pull request by jaredmorrow**

### CODE REVIEW

**Comment by bookshelfdave** [comment]
This seems to work fine:

```
[1]R15B01:[jem-rel-fixes]prime:~/test-releases/riak_cs/dev/dev1$ ./sbin/riak-cs console
...
```

But if I try to relocate it to /tmp/rt/current/cs:

```
[1]R15B01:[jem-rel-fixes]prime:~/test-releases/riak_cs/dev$ cp -R ./* /tmp/rt/current/cs/

...

[1]R15B01:prime:/tmp/rt/current/cs/dev1/sbin$ ./riak-cs console
./riak-cs: line 8: cd: ./riak-cs: Not a directory
./riak-cs: line 8: /lib/env.sh: No such file or directory
```

Also, will this PR https://github.com/basho/riak_cs/pull/289 affect what your doing?

**Comment by jaredmorrow** [comment]
It isn't the relocation that caused the problem, it was the running of the script from the sbin directory.  This caused the shell script to fail on the pattern.   I'll need to fix the shell script to allow for this.

**Comment by jaredmorrow** [comment]
Can you give my last commit a try @metadave, no rush on a weekend.

**Comment by bookshelfdave** [comment]
+1

**Pull request merged**
