### PR TITLE
Add Solaris and SmartOS support to riak-cs packaging

### PR DESCRIPTION
**Pull request by jaredmorrow**

### CODE REVIEW

**Comment by reiddraper** [comment]
I see a (new?) version of `rebar` in here, what version is it? We just updated recently.

**Comment by jaredmorrow** [comment]
@reiddraper it is head of rebar/rebar once Dizzy merged in @Vagabond 's mustache list support

**Comment by jaredmorrow** [comment]
This PR has been replaced by #447

**Comment by dizzyd** [comment]
I merged that a few days ago.

**Comment by jaredmorrow** [comment]
@dizzyd is always watching, and yes thanks for merging that!

**Comment by reiddraper** [comment]
@dizzyd hey how'd you get in here ;)?

**Pull request closed without merging**
