### PR TITLE
Merge 1.5.4

### PR DESCRIPTION
**Pull request by kuenishi**
It didn't get cleanly merged, so opening up a pull request for review.

### CODE REVIEW

**Comment by shino** [comment]
I don't understand the commit cbd83b2. The commit is included in the tag 1.5.4 (by PR #1049) so it seems that separate merge commit is not needed.

**Comment by shino** [comment]
Ah, there are a few such merge commit. Did you intend to merge per PR?

**Comment by kuenishi** [comment]
just a `git merge release/1.5` command didn't work for me - somewhat I was confused.

**Comment by shino** [comment]
I tested `git merge origin/release/1.5` at develop (afed87e).
The merge commit is 2dca113.
There is one conflict for the file `rtcs.erl` and it seems append to the end of file from both side.

**Comment by kuenishi** [comment]
I believe this time merge went well.

**Comment by kuenishi** [comment]
Riak test has passed for me, so maybe it's okay to merge?

**Comment by shino** [comment]
All riak_test cases passed! :fireworks:

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
