### PR TITLE
Reset xref and dialyzer ignore files

### PR DESCRIPTION
**Pull request by kuenishi**
Particularly if we move to a different version of Erlang, I think it's good practice to start fresh with our xref and dialyzer 'grep -v' files.

### CODE REVIEW

**Comment by kuenishi** [comment]
Here's the raw result of dyalizer: https://gist.github.com/kuenishi/6537524

**Comment by reiddraper** [comment]
Careful, this wants to merge into master.

**Comment by kuenishi** [comment]
Sorry! I'll open a new issue for convenience.

**Pull request closed without merging**
