### PR TITLE
fixed 'Missing application directory.'

### PR DESCRIPTION
**Pull request by namjae**
same as https://github.com/basho/stanchion/pull/82

### CODE REVIEW

**Comment by shino** [comment]
@namjae I don't understand what is wrong. Please give me some information.

For application directory settings, riak_cs uses old style (prior to R15B01)
`lib_dirs` [1] and symlinks under `apps/` directory [2].
What does the directory look like?

```
$ ls -al apps
total 12
drwxrwxr-x  3 shino 4096 Jul  8  2013 .
drwxr-xr-x 23 shino 4096 Jul 16 17:36 ..
drwxrwxr-x  2 shino 4096 Jul  8  2013 riak_cs
$ ls -al apps/riak_cs
total 8
drwxrwxr-x 2 shino 4096 Jul  8  2013 .
drwxrwxr-x 3 shino 4096 Jul  8  2013 ..
lrwxrwxrwx 1 shino   11 Jul  8  2013 ebin -> ../../ebin/
lrwxrwxrwx 1 shino   14 Jul  8  2013 include -> ../../include/
lrwxrwxrwx 1 shino   10 Jul  8  2013 priv -> ../../priv
lrwxrwxrwx 1 shino   10 Jul  8  2013 src -> ../../src/
```

[1] https://github.com/basho/riak_cs/blob/develop/rel/reltool.config#L4
[2] https://github.com/basho/riak_cs/tree/develop/apps/riak_cs

**Comment by shino** [comment]
Can not reproduce with the settings under:
- Erlang R16B03-1
- rebar `2.5.0 R14B04 20140716_092047 git 2.5.0-dirty` or the one in riak_cs repository

**Comment by shino** [comment]
Do you use Windows?

**Comment by namjae** [comment]
here's some additional info:
- OS: Ubuntu Server 14.04 LTS (64bit, fully updated today)
- rebar: downloaded from https://github.com/rebar/rebar/wiki/rebar 
- Erlang: Erlang R16B03-1 (built by kerl - https://github.com/yrashk/kerl)

i'm away from my box for now.
if you need some more info, leave a comment here.
i'll check the box and inform you.

**Comment by shino** [comment]
I will close this ticket because it can not be reproduced and the diff breaks backward compatibility (old OTP versions).

It's possible the described environment hits a corner case bug of riak cs's config, rebar, reltool, or thier combination. Please report and discuss about it at riak-users mailing list if you can reproduce this, with further infomation.
Thanks for contribution!

**Pull request closed without merging**
