### PR TITLE
Golang client test with s3gof3r

### PR DESCRIPTION
**Pull request by shino**
Add Go lang to client test lineup.

Add only one test case, which used s3gof3r and confirm
Content-MD5 of Complete Multipart Upload response and

Not like other client tests, test code is not implemented in Go but
just some lines in `Makefile`. This is because s3gof3r provides a
command line tool gof3r and go has standard way of placing libraries.

Of cource, the Go test target is added to top level `Makefile` and can
be executed both by `make test-client` and by riak_test
`external_client_tests`.

This PR addresses #889.

### CODE REVIEW

**Comment by kuenishi** [comment]
In my env:

``` sh
> LANG=C make
mkdir /home/kuenishi/src/riak_cs/client_tests/go/env
go get github.com/rlmcpherson/s3gof3r/gof3r
mkdir -p /home/kuenishi/src/riak_cs/client_tests/go/tmp
dd if=/dev/urandom of=/home/kuenishi/src/riak_cs/client_tests/go/tmp/rand-50MB bs=1M count=50
50+0 records in
50+0 records out
52428800 bytes (52 MB) copied, 4.4154 s, 11.9 MB/s
gof3r put --without-ssl -s 5242880 -p /home/kuenishi/src/riak_cs/client_tests/go/tmp/rand-50MB -b test -k 1403488321
gof3r error: unknown flag `without-ssl'
run 'gof3r put --help' for usage.
Makefile:23: recipe for target 'test-mp-put-get' failed
make: *** [test-mp-put-get] Error 1
```

something wrong in latest version of gof3r?

**Comment by kuenishi** [comment]
With the latest version, ssl option has changed:

```
> gof3r put --help
Usage:
  gof3r [OPTIONS] put [put-OPTIONS]

put (upload) data to S3 object

Application Options:
  -v, --version          Print version
  -m, --manpage          Create gof3r.man man page in current directory

Help Options:
  -h, --help             Show this help message

[put command options]
      -p, --path=        Path to file. Defaults to standard input for streaming.
      -k, --key=         S3 object key
      -b, --bucket=      S3 bucket
          --no-ssl       Do not use SSL for endpoint connection.
          --no-md5       Do not use md5 hash checking to ensure data integrity. By default, the md5 hash of is calculated concurrently during
                         puts, stored at <bucket>.md5/<key>.md5, and verified on gets.
      -c, --concurrency= Concurrency of transfers (10)
      -s, --partsize=    Initial size of concurrent parts, in bytes (20971520)
          --endpoint=    Amazon S3 endpoint (s3.amazonaws.com)
          --debug        Enable debug logging.
      -m, --header=      HTTP headers
```

**Comment by shino** [comment]
It seems the option name has changed yesterday.
https://github.com/rlmcpherson/s3gof3r/commit/06a28aaeb431d162061556793bfb690d1d5fe671

I will fix it.

**Comment by shino** [comment]
Pushed.

**Comment by shino** [comment]
@borshop merge

**Pull request merged**
