### PR TITLE
Fix empty object list with delimiter

### LINKED ISSUE #654: object list (GET Bucket) fails when first 1002 keys are all deleted
- With Riak 1.4.x and Riak CS 1.4.x.
- Enable `fold_objects_for_list_keys`.

Steps to reproduce:

```
$ s3cmd mb s3://test/
$ mkdir a
$ for i in {0001..1002}; do echo ${i} > a/${i}.txt; done   # in zsh
$ s3cmd put --recursive a s3://test
$ s3cmd del --recursive --force s3://test
$ s3cmd ls s3://test     # !!FAIL!!
```

Crash log

```
2013-08-26 16:37:28 =ERROR REPORT====
** State machine <0.12130.0> terminating 
** Last message in was {26551215,{done,<<"g20AAAAKYS8xMDAyLnR4dA==">>}}
** When State == waiting_object_list
**      Data  == {state,<0.271.0>,{list_objects_request_v1,<<"test">>,1000,undefined,<<"/">>,undefined}, [snip]
** Reason for termination = 
** {function_clause,[{lists,last,[[]],[{file,"lists.erl"},{line,162}]},{riak_cs_list_objects_fsm_v2,make_start_key,1,[{file,"/home/shino/work/basho/git/riak_cs-1.4/src/riak_cs_list_objects_fsm_v2.erl"},{line,359}]},{riak_cs_list_objects_fsm_v2,make_2i_request,2,[{file,"/home/shino/work/basho/git/riak_cs-1.4/src/riak_cs_list_objects_fsm_v2.erl"},{line,289}]},{riak_cs_list_objects_fsm_v2,respond,4,[{file,"/home/shino/work/basho/git/riak_cs-1.4/src/riak_cs_list_objects_fsm_v2.erl"},{line,252}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,494}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
```

Direct cause:

`CommonPrefixes` is empty at https://github.com/basho/riak_cs/blob/release/1.4/src/riak_cs_list_objects_fsm_v2.erl#L356 .

### PR DESCRIPTION
**Pull request by reiddraper**
Fixes #654

### CODE REVIEW

**Comment by shino** [comment]
When there are both some common prefixes and non-prefixed keys,
next start key is "rewinded" by `skip_past_prefix_and_delimiter`.

A situation is like this:
- 100 active objects under `0/`
- 1 active object whose name is `1.txt`
- 1000 `pending_delete` objects under `2/`

`ls` reports duplicated `1.txt`.

```
$ s3cmd ls s3://test
                       DIR   s3://test/0/
2013-08-27 02:09         9   s3://test/1.txt
2013-08-27 02:09         9   s3://test/1.txt
```

**Comment by reiddraper** [comment]
@shino nice catch! Working on a fix today.

**Comment by shino** [comment]
Found one more issue.

Infinite loop happens for list objects request with prefix _without_ delimiter.

Assume test bucket has 1100 active keys under prefix `0/`.
`s3cmd -c s3cfg.dev1.alice ls s3://test/0` (no slash at the end) does not respond
and CPU is used constantly even after killing s3cmd.

Here, it seems to be assumed that prefix ends with delimiter:
https://github.com/basho/riak_cs/blob/82fc60b75e1afbb4f2feb5ec3cec0c0461a35790/src/riak_cs_list_objects_fsm_v2.erl#L338

**Comment by reiddraper** [comment]
confirmed.

**Comment by reiddraper** [comment]
This also seems to have revealed a link/monitoring error. The object listing FSM doesn't stop if the HTTP connection gets closed.

**Comment by reiddraper** [comment]
The infinite loop was introduced in 82fc60b75e1afbb4f2feb5ec3cec0c0461a35790.

**Comment by reiddraper** [comment]
Ready for more review now.

**Comment by shino** [comment]
Change in source code seems nice!
Additonal riak_test passes.
+1 from me.

**Comment by reiddraper** [comment]
Excellent. I've asked @andrewjstone for a second review, given the number of bugs found so far.

**Comment by shino** [comment]
Thanks a lot @reiddraper! And I'm sorry for bothoring you day by day.

**Comment by reiddraper** [comment]
> And I'm sorry for bothoring you day by day.

Quite the opposite, these were great bugs to find :)

**Comment by andrewjstone** [comment]
@shino I second what reid said. Excellent bug finds.

**Comment by andrewjstone** [comment]
- [x] eunit + eqc
- [x] riak_test
- [x] dialyzer
- [x] xref

**Comment by shino** [comment]
Thanks a lot @reiddraper @andrewjstone !!

**Pull request merged**
