### PR TITLE
Update tools.mk and fix some xref/dialyzer issues

### PR DESCRIPTION
**Pull request by reiddraper**
@slfritchie, can you please double-check 6014262f028934537eb4f9773c0a3eba9b72268e?

### CODE REVIEW

**Comment by reiddraper** [comment]
One/if this is +1'd, I'll merge/rebase with develop, as it appears there will be a merge-conflict. I'm guessing it will be with rebar.config.

**Comment by reiddraper** [comment]
cc @Vagabond

**Comment by reiddraper** [comment]
I also realized we're not even allowing R14 in the rebar.config allowed versions, so 6014262f028934537eb4f9773c0a3eba9b72268e should be quite safe.

**Comment by reiddraper** [comment]
Force-pushed with a rebase from develop.

**Comment by Vagabond** [comment]
+1 dc1ebb1

**Comment by reiddraper** [comment]
@borshop merge

**Pull request merged**
