### PR TITLE
Feature/xmerl avoid undef rebased

### PR DESCRIPTION
**Pull request by reiddraper**
Subsumes #706. This is #706 rebased and with 0079a4a908757714baebef70e538fea936d324a7 added.

### CODE REVIEW

**Comment by kuenishi** [comment]
+1

**Comment by kuenishi** [comment]
+1 0079a4a

**Comment by kuenishi** [comment]
The error still remains since previous `.local_dialyzer_plt` still remaining? The error hasn't changed yet. Maybe recreating it makes test passing.

**Comment by reiddraper** [comment]
I had thought build-bot started from a fresh checkout, but maybe not. @jaredmorrow might know?

**Comment by reiddraper** [comment]
Ah, it's not the `.local_dialyzer_plt` that is causing issues, it's the global one:

```
==> build (compile)
  Checking whether the PLT /Users/buildbot/.riak-cs_dialyzer_plt is up-to-date... yes
done (passed successfully)
 yes
done (passed successfully)
  Creating PLT .local_dialyzer_plt ...
```

Simply deleting this file should fix the issue. I'm not sure which builder the CS tests run on, but would you mind deleting the file, or pinging me the hostname (offline) @jaredmorrow?

**Comment by jaredmorrow** [comment]
Fixed.

**Comment by kuenishi** [comment]
+1 0079a4a

**Comment by reiddraper** [comment]
Thanks @jaredmorrow.

**Comment by reiddraper** [comment]
@borshop merge

**Pull request merged**
