### PR TITLE
Refactor/multibag simpler state transition

### PR DESCRIPTION
**Pull request by shino**
Add UUID to `set_manifest` call argument. This leads to simplification in multibag riak client state transition.

This PR depends on #1079 and includes its commit. There is only one last commit for that is unique for this PR.

### CODE REVIEW

**Comment by kuenishi** [comment]
@borshop merge

**Comment by kuenishi** [comment]
no, don't.

**Comment by kuenishi** [comment]
@borshop merge

**Comment by shino** [comment]
#1079 is included in this merge.

**Pull request merged**
