### PR TITLE
Fix hard-coded crashdump path.

### PR DESCRIPTION
**Pull request by ksauzz**

### CODE REVIEW

**Comment by kuenishi** [comment]
``` sh
root@0c0652e32de6:/# riak-cs start
root@0c0652e32de6:/# ps aux|grep beam
riak      1893  7.6  0.3 5749096 111068 pts/0  Ssl+ 01:22   0:03 /usr/lib/riak/erts-5.10.3/bin/beam.smp -P 256000 -e 256000 -Q 65536 -A 64 -K true -W w -zdbbl 32768 -- -root /usr/lib/riak -progname riak -- -home /var/lib/riak -- -boot /usr/lib/riak/releases/2.0.0/riak -config /var/lib/riak/generated.configs/app.2015.01.20.01.22.26.config -setcookie riak -name riak@127.0.0.1 -smp enable -vm_args /var/lib/riak/generated.configs/vm.2015.01.20.01.22.26.args -pa /usr/lib/riak/lib/basho-patches -- console
riakcs    2506  3.2  0.2 881628 67380 pts/1    Ssl+ 01:22   0:00 /usr/lib/riak-cs/erts-5.10.3/bin/beam.smp -K true -A 64 -W w -- -root /usr/lib/riak-cs -progname riak-cs -- -home /var/lib/riak-cs -- -boot /usr/lib/riak-cs/releases/1.5.3/riak-cs -config /etc/riak-cs/app.config -name riak-cs@127.0.0.1 -setcookie riak -vm_args /etc/riak-cs/vm.args -pa /usr/lib/riak-cs/lib/basho-patches -- console
root      2810  0.0  0.0   8872   780 ?        S+   01:23   0:00 grep --color=auto beam
root@0c0652e32de6:/# kill -SIGUSR1 2506
root@0c0652e32de6:/# ps aux|grep beam                                                                 
riak      1893  6.4  0.3 5750120 111296 pts/0  Ssl+ 01:22   0:03 /usr/lib/riak/erts-5.10.3/bin/beam.smp -P 256000 -e 256000 -Q 65536 -A 64 -K true -W w -zdbbl 32768 -- -root /usr/lib/riak -progname riak -- -home /var/lib/riak -- -boot /usr/lib/riak/releases/2.0.0/riak -config /var/lib/riak/generated.configs/app.2015.01.20.01.22.26.config -setcookie riak -name riak@127.0.0.1 -smp enable -vm_args /var/lib/riak/generated.configs/vm.2015.01.20.01.22.26.args -pa /usr/lib/riak/lib/basho-patches -- console
root      2812  0.0  0.0   8872   928 ?        S+   01:23   0:00 grep --color=auto beam
root@0c0652e32de6:/# ls /var/log/riak-cs/
console.log  crash.log  erl_crash.dump  erlang.log.1  error.log  run_erl.log
root@0c0652e32de6:/# head /var/log/riak-cs/erl_crash.dump 
=erl_crash_dump:0.2
Tue Jan 20 01:23:23 2015
Slogan: Received SIGUSR1
System version: Erlang R16B02-basho5 (erts-5.10.3) [source] [64-bit] [smp:8:8] [async-threads:64] [kernel-poll:true]
Compiled: Tue Aug 26 21:44:20 2014
Taints: dyntrace
Atoms: 13734
=memory
total: 96023440
processes: 5925368
```

Okay

**Comment by kuenishi** [comment]
This issue addresses #1001 .

**Comment by ksauzz** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
merged 

**_[posted via JIRA by Kota Uenishi]**_

**Pull request merged**
