### PR TITLE
Add GET Bucket Location API

### PR DESCRIPTION
**Pull request by kuenishi**
Although this patch doesn't support setting location constraints in buckets.

### CODE REVIEW

**Comment by kuenishi** [comment]
Needs https://github.com/basho/erlcloud/pull/14 to pass the updated riak_test.

**Comment by Basho-JIRA** [comment]
Needs review 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by shino** [comment]
All riak_test cases passed for both basic and mb flavors.

**Comment by shino** [comment]
@borshop merge

**Pull request merged**
