### PR TITLE
Feature/update clojure test

### PR DESCRIPTION
**Pull request by shino**
This PR's main purpose is to update version of aws-sdk-java in client tests to latest `1.10.8`.

As side effects...
- Use proxy settings in upstream master https://github.com/weavejester/clj-aws-s3
  instead of proxy support by forked one
- Include `s3.clj` from clj-aws-s3 repository (at commit `b01c0f1`)
  because it is single file thin wrapper, no test and to make updating easier.
- Update other dependent library versions

### CODE REVIEW

**Comment by shino** [comment]
Refactored code, added a little doc fix. Ready for review now.

**Comment by ksauzz** [comment]
So this updates aws-adk-java from 1.4.7 to 1.10.8.

**Comment by ksauzz** [comment]
@borshop merge

**Comment by kuenishi** [comment]
RCS-255 (#1208)

**Pull request merged**
