### PR TITLE
Merging with 2.0 branch [JIRA: RCS-294]

### PR DESCRIPTION
**Pull request by ksauzz**

### CODE REVIEW

**Comment by kuenishi** [comment]
create jira issue

**Comment by kuenishi** [comment]
Hey @Basho-JIRA , why do you change issue title that doesn't make sense?

**Comment by kuenishi** [comment]
@borshop: retry

**Comment by kuenishi** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
No need to write a release note 

**_[posted via JIRA by Kota Uenishi]**_

**Pull request merged**
