### PR TITLE
Merge 1.4.5 into develop

### PR DESCRIPTION
**Pull request by reiddraper**
Opening this as a PR because there were some merge-conflicts, and I'd appreciate a second pair of eyes on it. I've run all the tests except riak_test, which is running in the background now.

### CODE REVIEW

**Comment by reiddraper** [comment]
the external_clients test is a little flaky on my box, but it does pass most of the time. Everything else passes fine.

**Comment by andrewjstone** [comment]
- [x] eunit  +  eqc
- [x] dialyzer
- [x] riak_test
- [x] xref
- [x] code inspection

**Comment by andrewjstone** [comment]
The following r_t run was against riak_ee 2.0/develop branch on OSX Mavericks. 
Those 2 tests have failed repeatedly for me, so no big deal.

```
Test Results:
user_test-error,riak_kv_bitcask_backend                  : pass
too_large_entity_test-error,riak_kv_bitcask_backend      : pass
storage_stats_test-error,riak_kv_bitcask_backend         : pass
stats_test-error,riak_kv_bitcask_backend                 : pass
stanchion_switch_test-error,riak_kv_bitcask_backend      : pass
repl_test-error,riak_kv_bitcask_backend                  : fail
object_get_test-error,riak_kv_bitcask_backend            : pass
object_get_conditional_test-error,riak_kv_bitcask_backend: pass
mp_upload_test-error,riak_kv_bitcask_backend             : pass
list_objects_v2_test-error,riak_kv_bitcask_backend       : pass
list_objects_test-error,riak_kv_bitcask_backend          : pass
external_client_tests-error,riak_kv_bitcask_backend      : fail
cs_781_regression_test-error,riak_kv_bitcask_backend     : pass
cs_654_regression_test-error,riak_kv_bitcask_backend     : pass
cs_631_regression_test-error,riak_kv_bitcask_backend     : pass
cs743_regression_test-error,riak_kv_bitcask_backend      : pass
cs512_regression_test-error,riak_kv_bitcask_backend      : pass
cs436_regression_test-error,riak_kv_bitcask_backend      : pass
cs347_regression_test-error,riak_kv_bitcask_backend      : pass
cs296_regression_test-error,riak_kv_bitcask_backend      : pass
access_stats_test-error,riak_kv_bitcask_backend          : pass
---------------------------------------------
2 Tests Failed
19 Tests Passed
That's 90.47619047619048% for those keeping score
```

**Comment by andrewjstone** [comment]
Following is the only relevant dialyzer warning:
`riak_cs_block_server.erl:337: Function get_block_remote/5 has no local return`

**Comment by reiddraper** [comment]
> Following is the only relevant dialyzer warning: [...]

Yes, and it's present on develop too. I have not been able to solve it yet. It did seem to disappear on a hipe-compiled Erlang though. Shrug.

**Comment by andrewjstone** [comment]
Ok. In that case :+1:

**Pull request merged**
