### PR TITLE
reorganize cli tools and introduce riak-cs-admin

### PR DESCRIPTION
**Pull request by ksauzz**
I'm wondering Riak CS provides a administration cli tool like riak-admin and current tool should migrate into it.

_This PR was extracted from #826._

### CODE REVIEW

**Comment by kuenishi** [comment]
@ksauzz is this ready-to-pull ?

**Comment by ksauzz** [comment]
@kuenishi Yes. I've waited for review. :sunglasses:

**Comment by kuenishi** [comment]
Would you mind adding tests like [riak-admin](https://github.com/basho/riak_test/blob/master/tests/riak_admin_console_tests.erl) ?

**Comment by kuenishi** [comment]
+1 4033143

**Comment by kuenishi** [comment]
@ksauzz you should rebase to the latest develop since #848 was merged after this PR had opened.

**Comment by ksauzz** [comment]
@kuenishi  Although it's done, `make dialyzer` on buildbot still failed. He seems to have to run `make cleanplt`.

**Comment by kuenishi** [comment]
Could you run `make cleanplt` , @jaredmorrow ?

**Comment by kuenishi** [comment]
Note: after #848 merged, pushing any more commits without rebasing to develop  or running CI tests will break the plt file in our CI environment. Please rebase to develop, or branch including #848 .

**Comment by kuenishi** [comment]
+1 4fb0503

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
