### PR TITLE
Old object shows up after delete the latest

### PR DESCRIPTION
**Pull request by shino**
```
$ git show  --decorate | head -6
commit 41c81d4f10c59034ae1ba22ec5a4af1b303efb91 (HEAD, origin/develop, origin/HEAD, develop)
Merge: ff790c2 c404aa1
Author: Kelly McLaughlin <kelly@basho.com>
Date:   Thu Mar 21 09:46:21 2013 -0600

    Merge branch 'feature/configurable-pb-connect-timeout' into develop
```

First, put twice:

```
$ s3cmd la


$ echo "OLD" > data.local/1
$ s3cmd put data.local/1 s3://test
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
data.local/1 -> s3://test/1  [1 of 1]
 4 of 4   100% in    0s   286.16 B/s  done
$ s3cmd get s3://test/1 -
s3://test/1 -> <stdout>  [1 of 1]
OLD
 4 of 4   100% in    0s   216.59 B/s  done
$ echo "NEW" > data.local/1
$ s3cmd put data.local/1 s3://test
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
data.local/1 -> s3://test/1  [1 of 1]
 4 of 4   100% in    0s   230.60 B/s  done
$ s3cmd get s3://test/1 -
s3://test/1 -> <stdout>  [1 of 1]
NEW
 4 of 4   100% in    0s   236.07 B/s  done
```

After del it, old object shows up:

```
$ s3cmd del s3://test/1
File s3://test/1 deleted
$ s3cmd get s3://test/1 -
s3://test/1 -> <stdout>  [1 of 1]
OLD
 4 of 4   100% in    0s   413.61 B/s  done
```

One more del, object disappears:

```
$ s3cmd del s3://test/1
File s3://test/1 deleted
$ s3cmd la


```

### CODE REVIEW

**Comment by reiddraper** [comment]
This gc code has caused several problems in the past, despite being refactored. Let's make sure to add some good tests during this cycle as well.

**Comment by shino** [comment]
Now @andrewjstone is working on this issue. This is left for bug report. Attached PR is stale so please ignore it.
(I want to remove PR if possible. )

@reiddraper Sure. There is one test case I have no idea, to assert first PUTted object is no longer `active` after second PUT. The first PUT is not visible via HTTP GET whether it's `active` or `(pending|scheduled)_delete`. 
Someone has any good idea? Can be done by unit test?

**Comment by andrewjstone** [comment]
@shino @reiddraper I wrote a riak_test test for this scenario.

https://github.com/basho/riak_cs/commit/dd9f59f117b0592ff9705857d7f6fc76fc991f68 

It would probably be a good idea to have more individual unit tests also. I think overall as I start refactoring more I will add them. I'm still working on the fix. It's almost done, but I'm going to refactor the fix also after I get this failing test to pass.

**Comment by shino** [comment]
Fixed by #518 .
Close this #512.

**Pull request closed without merging**
