### PR TITLE
Make fold_objects the default in Riak CS

### PR DESCRIPTION
**Pull request by reiddraper**

### CODE REVIEW

**Comment by reiddraper** [comment]
Ready for some review here.

**Comment by andrewjstone** [comment]
Looks good to me. Running tests.

**Comment by andrewjstone** [comment]
- [x] eunit + eqc
- [x] riak_test

:+1:

**Comment by shino** [comment]
Some more changes needed?
- The default value `FOLD_OBJECTS_FOR_LIST_KEYS` in `list_objects.hrl`
- Adding custom config to `list_objects_test.erl`.
  Current `list_objects_v2_test.erl` has its own custom setting
  `{cs, rtcs:cs_config([{fold_objects_for_list_keys, true}])}` 

I will make PR of those. Please tell me if there are any others.

**Comment by reiddraper** [comment]
> I will make PR of those. Please tell me if there are any others.

Thanks, yeah I forgot those.

**Pull request merged**
