### PR TITLE
Prepare release notes (#964 is likely to merge)

### PR DESCRIPTION
**Pull request by kuenishi**
#964 is not yet merged, but it's be likely to be merged. Please feel free to correct my English.

### CODE REVIEW

**Comment by shino** [comment]
https://github.com/basho/riak_cs/pull/957 is missing

Looks nice other than that.

**Comment by kuenishi** [comment]
No, please don't merge. waiting for native reviews.

**Comment by kuenishi** [comment]
I deleted shino's merge comment.

**Comment by shino** [comment]
:sweat:

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
