### PR TITLE
Add symlink support

### PR DESCRIPTION
**Pull request by seryl**

### CODE REVIEW

**Comment by seryl** [comment]
This ticket is part of a pull request that had started re: homebrew.

https://github.com/mxcl/homebrew/pull/18669

A seperate, independent pull request is required for node_package: https://github.com/basho/node_package/pull/46

Adds support for symlinks, it should work for riak-cs and stanchion.

I am not super familiar with the build process, but I'd like to get this tested and eventually merged.

Is there anyone who can give a little input? I can at a minimum test centos and osx.

**Comment by reiddraper** [comment]
@jaredmorrow any ideas here?

**Comment by jaredmorrow** [comment]
@reiddraper there are no fewer than 3 PR's in homebrew itself about this topic.  I was waiting for them to be merged so I can take the winner and add that to node_package

**Comment by reiddraper** [comment]
> @reiddraper there are no fewer than 3 PR's in homebrew itself about this topic. I was waiting for them to be merged so I can take the winner and add that to node_package

Cool, sounds good to me.

**Comment by reiddraper** [comment]
Any updates to this, or is it still waiting for some homebrew changes?

**Comment by jaredmorrow** [comment]
This is being solved with patches AFAIK in homebrew now, so I'm going to close this.

**Pull request closed without merging**
