### PR TITLE
Use short http keepalive in erlcloud

### PR DESCRIPTION
**Pull request by reiddraper**
Use `wrd-http-options` erlcloud branch for testing
- Passes in short http keepalive to erlcloud (to further be passed
  to httpc)
- Grabs proxy host and port from http options instead of aws_config

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
The `rtcs` module for `riak_test` needs to be updated to use `erlcloud_s3:new/8` or the `riak_test` runs will get an `undef` error.

**Comment by kellymclaughlin** [comment]
+1 to merge pending approval of my last commit

**Comment by reiddraper** [comment]
Waiting for #427 to make it in, and then will rebase this off of that, to be able to test w/ riak_test.

**Comment by reiddraper** [comment]
Yay, riak_test passing

**Pull request merged**
