### PR TITLE
Update webmachine, riakc, poolboy and riak_repl_pb_api. Pin multibag. [JIRA: RCS-143]

### PR DESCRIPTION
**Pull request by kuenishi**
...for upcoming code freeze. Pinned as 2.0.0 in reltool.config. Maybe https://github.com/basho/eper/pull/11 will follow later.

### CODE REVIEW

**Comment by kuenishi** [comment]
ping @Basho-JIRA

**Comment by shino** [comment]
@borshop merge

**Comment by shino** [comment]
No. Wrong issue.

**Comment by shino** [comment]
Tested with https://github.com/basho/riak_cs_multibag/pull/22 by checking out its branch manually.
All riak_test passed :fireworks: 

I will :+1: after that PR is merged and tagged.

**Comment by kuenishi** [comment]
Updated multibag.

**Comment by kuenishi** [comment]
... and tagged.

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
