### PR TITLE
Update ceph tests to the latest version.

### PR DESCRIPTION
**Pull request by ksauzz**
https://github.com/basho/s3-tests/pull/2 is needed to pass the tests.

### CODE REVIEW

**Comment by kuenishi** [comment]
Addresses #1085 (RCS-134).

**Comment by kuenishi** [comment]
Not a bug of this pull request, but I'd like this patched:

``` diff
diff --git a/client_tests/python/boto_tests/boto_test.py b/client_tests/python/boto_tests/boto_test.py
index dbfa39c..bfbef4c 100755
--- a/client_tests/python/boto_tests/boto_test.py
+++ b/client_tests/python/boto_tests/boto_test.py
@@ -33,6 +33,8 @@ import boto

 def setup_auth_scheme():
     auth_mech=os.environ.get('CS_AUTH', 'auth-v2')
+    if not boto.config.has_section('s3'):
+        boto.config.add_section('s3')
     if auth_mech == 'auth-v4':
         setup_auth_v4()
     else:
@@ -41,13 +43,11 @@ def setup_auth_scheme():
 def setup_auth_v4():
     print('Use AWS Version 4 authentication')
     if not boto.config.get('s3', 'use-sigv4'):
-        boto.config.add_section('s3')
         boto.config.set('s3', 'use-sigv4', 'True')
```

This code conflicted with my `~/.boto` s3 section.

**Comment by kuenishi** [comment]
I'll do +1 if above patch merged. Good job.

**Comment by kuenishi** [comment]
all r_t has passed

**Comment by kuenishi** [comment]
@borshop merge

**Comment by kuenishi** [comment]
@ksauzz Pleas list up _all_ issues found via your work here.

**Comment by ksauzz** [comment]
1. [Unnecessary NextMarker](https://github.com/basho/riak_cs/issues/1099)
2. CS should respond 'Not Found' if bucket is not existed. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L2381-L2394))
3. Support non-canned ACL. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L3313-L3332)) 
4. CS should respond 'InvalidAccessKeyId' if non-existent key id is sent. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L4203-L4213))
5. CS should responds 'SignatureDoesNotMatch' if a signature is not match. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L4215-L4225))
6.  [Copy API should copy user meta data.](https://github.com/basho/riak_cs/issues/1097)
7. [CS should refuse a empty request on multipart completion.](https://github.com/basho/riak_cs/issues/1100)
8. CS should respond NoSuchUpload. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L4619-L4626))

**Comment by kuenishi** [comment]
Thanks (thumbup)

**Pull request merged**
