### PR TITLE
WIP: Introduce riak-cs-admin

### PR DESCRIPTION
**Pull request by ksauzz**
RiakCS has various CLI tools and they are expected to increase number of them gradually in future. To avoid increasing the number of them I suggest introducing riak-cs-admin into RiakCS as administration CLI like riak-admin for Riak. Changes on this PR include follows:
- riak-cs-admin
  - move the implementation of existing tools into riak-cs-admin
  - leave existing tools as adopter to riak-cs-admin for a while, just in case.
  - add cluster-info to riak-cs-admin
- new stats format
  - add new stats to riak-cs-admin with the same format of `riak-admin status` and also `/stats`. 
  - add config `stats_format` to switch a stats format and keep backward compatibility.
- riak-cs-debug
  - add riak-cs-debug

TODO
- [x] how to deal with current `/stats` API's format ?
  - option1: switch it by config `{cs_stats_version, v2}`
  - option2: switch it by url param `/stats?v2` or `/stats/v2
- [x] how to add riak-cs-debug, this subcommand or not ? It looks like too large code base to add riak-cs-admin as its subcommand.
- [ ] regression test.
#### riak-cs-admin

```
% ./riak-cs-admin
Usage: riak-cs-admin { status | cluster-info | gc | access | storage | stanchion }
```
##### sub commands

```
% ./riak-cs-admin status | head
1-minute stats for 'riak-cs@127.0.0.1'
-------------------------------------------
block_get_total : 0
block_get_rate : 0.0
block_get_time_mean : 0.0
block_get_time_median : 0.0
block_get_time_95 : 0.0
block_get_time_99 : 0.0
block_get_retry_total : 0
block_get_retry_rate : 0.0
```

```
% ./riak-cs-admin cluster-info
Usage: riak-cs-admin cluster-info <output_file>
```

```
% ./riak-cs-admin gc
Usage: riak-cs-admin gc { batch [<leeway_seconds>] | status | pause | resume | cancel |
                          set-interval <interval_seconds> | set-leeway <leeway_seconds> }
```

```
% ./riak-cs-admin access
Usage: riak-cs-admin access  { flush }
```

```
% ./riak-cs-admin storage
Usage: riak-cs-admin storage  { batch | status | pause | resume | cancel }
```

```
% ./riak-cs-admin stanchion
Usage: riak-cs-admin stanchion  { switch HOST PORT | show }
```
#### v0

```
% ./riak-cs-admin status
           block_get:   0       0.0     0.0     0.0     0.0     0.0
     block_get_retry:   0       0.0     0.0     0.0     0.0     0.0
           block_put:   0       0.0     0.0     0.0     0.0     0.0
        block_delete:   0       0.0     0.0     0.0     0.0     0.0
 service_get_buckets:   0       0.0     0.0     0.0     0.0     0.0
    bucket_list_keys:   0       0.0     0.0     0.0     0.0     0.0
       bucket_create:   0       0.0     0.0     0.0     0.0     0.0
       bucket_delete:   0       0.0     0.0     0.0     0.0     0.0
      bucket_get_acl:   0       0.0     0.0     0.0     0.0     0.0
      bucket_put_acl:   0       0.0     0.0     0.0     0.0     0.0
          object_get:   0       0.0     0.0     0.0     0.0     0.0
          object_put:   0       0.0     0.0     0.0     0.0     0.0
         object_head:   0       0.0     0.0     0.0     0.0     0.0
       object_delete:   0       0.0     0.0     0.0     0.0     0.0
      object_get_acl:   0       0.0     0.0     0.0     0.0     0.0
      object_put_acl:   0       0.0     0.0     0.0     0.0     0.0
```

```
% s3cmd -c user.cfg get s3://riak-cs/stats - | jsonpp | head -15
{
  "legend": [
    "meter_count",
    "meter_rate",
    "latency_mean",
    "latency_median",
    "latency_95",
    "latency_99"
  ],
  "block_get": [
    0,
    0.0,
    0.0,
    0.0,
    0.0,
```
##### v1

```
% ./riak-cs-admin status | head
1-minute stats for 'riak-cs@127.0.0.1'
-------------------------------------------
block_get_total : 0
block_get_rate : 0.0
block_get_time_mean : 0.0
block_get_time_median : 0.0
block_get_time_95 : 0.0
block_get_time_99 : 0.0
block_get_retry_total : 0
block_get_retry_rate : 0.0
```

```
% s3cmd -c user.cfg get s3://riak-cs/stats - | jsonpp | head -15
{
  "block_get_total": 0,
  "block_get_rate": 0.0,
  "block_get_time_mean": 0.0,
  "block_get_time_median": 0.0,
  "block_get_time_95": 0.0,
  "block_get_time_99": 0.0,
  "block_get_retry_total": 0,
  "block_get_retry_rate": 0.0,
  "block_get_retry_time_mean": 0.0,
  "block_get_retry_time_median": 0.0,
  "block_get_retry_time_95": 0.0,
  "block_get_retry_time_99": 0.0,
  "block_put_total": 0,
  "block_put_rate": 0.0,
```

### CODE REVIEW

**Comment by shino** [comment]
@ksauzz Can we close this in favor of other PRs above? Or more issues/PRs needed?

**Comment by kuenishi** [comment]
stats.

On Friday, May 16, 2014, Shunichi Shinohara notifications@github.com
wrote:

> @ksauzz https://github.com/ksauzz Can we close this in favor of other
> PRs above? Or more issues/PRs needed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak_cs/pull/826#issuecomment-43289453
> .

## 

Sent from Gmail Mobile

**Comment by kuenishi** [comment]
Stats to be another issue and closing this one would be good? @ksauzz

**Comment by ksauzz** [comment]
@kuenishi sounds good.

**Pull request closed without merging**
