### PR TITLE
Remove key_context used in riak_cs_wm_object

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Remove `key_context` and replace with a new general purpose `local_context` field in the context record.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
@jrwest Check this out and lemme know what you think. Feel free to merge it into the branch if you like it or I can do it.

**Comment by jrwest** [comment]
looks good. ill merge it tomorrow when i work on a couple of the other object resources. btw, any objection to renaming `key_context` to `object_context` since we renamed the resource from `wm_key` to `wm_object`?

EDIT: hit enter to soon.

**Comment by jrwest** [comment]
ended up running into a couple minor things. going to make some changes on this branch and push before merging.

**Comment by jrwest** [comment]
@kellymclaughlin pushed a few changes that i mostly had locally before your changes plus a few things i ran into while testing `s3cmd put`. if they look good to you ill merge it in this weekend (or feel free if you get to it before me).

**Comment by kellymclaughlin** [comment]
Your changes look good to me. Merge away.

**Pull request merged**
