### PR TITLE
Enable stat in riak_test

### PR DESCRIPTION
**Pull request by shino**

### CODE REVIEW

**Comment by slfritchie** [comment]
Shino, is that why the riak_test/src/stats_test.erl has been failing for me?

**Comment by shino** [comment]
@slfritchie What was your error?

The error of stats_test for me was:

```
2013-03-11 13:14:29.348 [error] <0.266.0> Supervisor poolboy_sup had child riak_cs_riakc_pool_worker started with riak_cs_riakc_pool_worker:start_link([{name,{local,bucket_list_pool}},{worker_module,riak_cs_riakc_pool_worker},{size,5},{max_overflow,...},...])
at undefined exit with reason shutdown in context shutdown_error
```

If the same error you got, probably the same reason.

**Comment by slfritchie** [comment]
Hrm, no, actually, I see this, no output from the `curl` command.  If I use that command manually and add a `-v` flag, I see CS returning a 503 error.

```
13:59:02.491 [debug] Querying stats
13:59:02.530 [info] Stats query cmd: "curl -s -H 'Date: Sun, 10 Mar 2013 18:59:02 GMT' -H 'Authorization: AWS PJCHL37V_C153K0RWOEO:6QuHBXjh+TyHgd9SemvSV38XiwU=' http://localhost:8071/riak-cs/stats"
13:59:02.617 [debug] Stats output=[]
13:59:02.617 [warning] stats_test failed: {{badmatch,any},[{mochijson2,tokenize,2,[{file,"src/mochijson2.erl"},{line,556}]},{mochijson2,decode1,2,[{file,"src/mochijson2.erl"},{line,312}]},{mochijson2,json_decode,2,[{file,"src/mochijson2.erl"},{line,307}]},{stats_test,query_stats,2,[{file,"riak_test/tests/stats_test.erl"},{line,43}]},{stats_test,confirm,0,[{file,"riak_test/tests/stats_test.erl"},{line,12}]}]}
13:59:02.618 [error] 
================ stats_test failure stack trace =====================
{{badmatch,any},
 [{mochijson2,tokenize,2,[{file,"src/mochijson2.erl"},{line,556}]},
  {mochijson2,decode1,2,[{file,"src/mochijson2.erl"},{line,312}]},
  {mochijson2,json_decode,2,[{file,"src/mochijson2.erl"},{line,307}]},
  {stats_test,query_stats,2,
              [{file,"riak_test/tests/stats_test.erl"},{line,43}]},
  {stats_test,confirm,0,[{file,"riak_test/tests/stats_test.erl"},{line,12}]}]}
=====================================================================
```

Here's the `curl` output.  There are no errors or other messages in the CS `erlang.log` file.

```
curl -v -s -H 'Date: Sun, 10 Mar 2013 18:59:02 GMT' -H 'Authorization: AWS PJCHL37V_C153K0RWOEO:6QuHBXjh+TyHgd9SemvSV38XiwU=' http://localhost:8071/riak-cs/stats
* About to connect() to localhost port 8071 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* connected
* Connected to localhost (127.0.0.1) port 8071 (#0)
> GET /riak-cs/stats HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
> Host: localhost:8071
> Accept: */*
> Date: Sun, 10 Mar 2013 18:59:02 GMT
> Authorization: AWS PJCHL37V_C153K0RWOEO:6QuHBXjh+TyHgd9SemvSV38XiwU=
> 
< HTTP/1.1 503 Service Unavailable
< Server: Riak CS
< Date: Mon, 11 Mar 2013 06:17:50 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
* Closing connection #0
```

**Comment by shino** [comment]
Oh, I forgot to mention _where_, sorry. The error I pasted was in console.log.

HTTP response stateus `503 Service Unavailable` is the same.
So I think the same cause.

**Comment by shino** [comment]
When I started riak_cs in console and GETted /riak-cs/stats by curl, `riak_cs_riakc_pool_worker` error did NOT occur.
The error occurred by different reason. I must dig it.

**Comment by shino** [comment]
Notes on `riak_cs_riakc_pool_worker` error.
- By console.log of riak_cs and riak_test log,  it is triggered by `riak_cs stop`.
- It does not always occur. (probably timing issue)
- It occurs after this PR change.

So the error is not related to stats_test, but to shutdown sequence, I think.

**Comment by kellymclaughlin** [comment]
I think I messed this up as part of [this](https://github.com/basho/riak_cs/commit/c740cee90b1f1ec4fc86167f463ccf1d8385da0e) commit. I think it will be the case that the majority of users would like stats enabled so how about making the default `true` [here](https://github.com/basho/riak_cs/blob/release/1.3/src/riak_cs_wm_stats.erl#L77) and then we do not need to modify the config overrides in `rtcs` because it will already be set in the devrel node configs.

**Comment by shino** [comment]
@kellymclaughlin  I thought  you intended to disable stats. I will change default value and throw away the commit I pushed.

**Comment by kellymclaughlin** [comment]
Thanks @shino! I removed that app.config entry because I thought it was `true` by default, but I was mistaken.

**Comment by shino** [comment]
Changed default value and force-push'ed.

**Comment by kellymclaughlin** [comment]
+1 to merge

**Comment by shino** [comment]
merged #482

**Pull request merged**
