### PR TITLE
Introduce getopt into riak_cs_inspector [JIRA: RCS-132]

### PR DESCRIPTION
**Pull request by shino**
`getopt` based riak_cs_inspector.

Before this PR, it was hard to change the script even if the change was minimal one.
This enables future enhancement in main line.

Based on @ksauzz 's work.

### CODE REVIEW

**Comment by shino** [comment]
This also includes R16B compatibility (warning suppression about `crypto:md5`).

**Comment by kuenishi** [comment]
I'd say command names are ... `users`, `objects`, `buckets` and `blocks`.

**Comment by kuenishi** [comment]
Anyway it's great work. Sooner or later let's improve this as an internal inspection tool for operators.

**Comment by kuenishi** [comment]
@borshop merge

**Pull request merged**
