### PR TITLE
Support virtual hosting with custom domain.

### PR DESCRIPTION
**Pull request by tsubosaka**
This pull request for supporting virtual-hosting with custom domain #1035 , and also fix bug #1036 .
For backward compatibility, it check new paraeter "support_customdomain_for_bucket" is true.

### CODE REVIEW

**Comment by kuenishi** [comment]
First of all if we support virtual hosting, there should be name server's CNAME checking - and only hostnames with valid DNS record should be accepted. And we need a little bit more discussion on how to validate. Maybe resolving the CNAME and caching the result with TTL would be the answer. And a few comments:
- This PR should point to develop branch
- Before supporting virtual domains we should introduce `Host` header validation.

**Comment by tsubosaka** [comment]
@kuenishi Sorry I missed your comment.

> This PR should point to develop branch

Ok, I retry PR.
And separate pull request into bug fix and feature enhancement.

> Maybe resolving the CNAME and caching the result with TTL would be the answer.
> ・Before supporting virtual domains we should introduce Host header validation.

Yes, but it add a little latency at system. So if we use this validation, this feature should be optional.

**Comment by shino** [comment]
>  if we support virtual hosting, there should be name server's CNAME checking - and only hostnames with valid DNS record should be accepted

Is it a spec of AWS S3? Are there some design/security concerns?

**Comment by kuenishi** [comment]
Yes, my concern is security, like some bad nameserver a.charlie.com CNAME pointing alice.example.com.s3.amazonaws.com. What happens in this case?

**Comment by shino** [comment]
I think nothing wrong happens.

AWS S3's specification for virtual hosting [1] says only about Host
header.  I guess it does not care whether users either use DNS/CNAME
or just use `cURL` and `-H` option manually.

Roughly speaking, S3 treats Host header as bucket name as whole if
it is not `s3.amazonaws.com`. Then it auth/authz as its way (ACL/Policy).
Using CNAME is _just an example_ of how to combine this S3 spec/behavior
with other services or environment.

[1] Virtual Hosting of Buckets - Amazon Simple Storage Service http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingSpecifyBucket

**Comment by kuenishi** [comment]
ok. I think I was sort of caremad.

**Comment by NoKriK** [comment]
Hi,

I'm interested by this feature, any news?

**Comment by kuenishi** [comment]
Stale. If this is strongly needed again, PR should be open against develop branch.

**Pull request closed without merging**
