### PR TITLE
Bump node_package to 3.0.0

### PR DESCRIPTION
**Pull request by jadeallenx**
This PR incorporates the updates to node_package that are going into the new riak releases. See also basho/stanchion#109 JIRA RCS-357 basho/node_package#196 basho/node_package#200

### CODE REVIEW

**Comment by tburghart** [comment]
Just a note lest anyone approve this right away - node_package version is about to change, so hands off until it's settled

**Comment by kuenishi** [comment]
+1 c6863d7

**Comment by tburghart** [comment]
+1  ee8260e

**Comment by jadeallenx** [comment]
@borshop merge

**Pull request merged**
