### PR TITLE
Add cluster-info

### PR DESCRIPTION
**Pull request by ksauzz**
Add riak-cs-cinfo as a command-line tool to get cluster-info. 

_This PR was extracted from #826._

### CODE REVIEW

**Comment by kuenishi** [comment]
So you're gonna merge this _before_ `riak-cs-admin` merged?

**Comment by ksauzz** [comment]
yes. I'm planing to split riak-cs-admin's PR into 4 PRs as following. It's easy to review and merge it.
1. this one.
2. Add `riak-cs-debug`
3. Add `riak-cs-admin` if it's acceptable, then remove `riak-cs-cinfo`.
4. Add `riak-cs-admin status` and improvement of `/stats`

**Comment by kuenishi** [comment]
~~To include the command into release package (.deb, .rpm and else) you have to add entry into pkg.vars.config for node_package, but it's missing. #831 recovers pkg.vars.config .~~

**Comment by kuenishi** [comment]
You have to add entry into rebar.config.script so that node_package can include the new command into packages.

**Comment by ksauzz** [comment]
done :thumbsup: thanks!

**Comment by kuenishi** [comment]
r_t passed for me.

**Comment by kuenishi** [comment]
Let me cancel my +1, I tried `make package` but there were no riak-cs-cinfo command installed inside .deb file. There must be a few things we missed.

**Comment by kuenishi** [comment]
With some temporary tagging it worked.

**Comment by kuenishi** [comment]
+1 9375b08

**Comment by ksauzz** [comment]
@borshop merge

**Pull request merged**
