### PR TITLE
Pin multibag as 2.1.0 [JIRA: RCS-295]

### PR DESCRIPTION
**Pull request by kuenishi**

### CODE REVIEW

**Comment by kuenishi** [comment]
create jira issue

**Comment by kuenishi** [comment]
@borshop: retry

**Comment by kuenishi** [comment]
@borshop merge

**Comment by kuenishi** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
No need to write a release note. 

**_[posted via JIRA by Kota Uenishi]**_

**Pull request merged**
