### PR TITLE
Support multipart manifest in "First Block" column in "object list"

### PR DESCRIPTION
**Pull request by shino**
Also add "Type" column which shows normal (non-multipart) or multipart.

Sample output:

```
Key ============================: Sibl. == State ========== UUID =========================== Content-Length== Type ==== First Block ====
mp                              : 1        active           fe2f7a37d633457ab34fa80ff0df8927         10485760 multipart Found
mp-no-blocks                    : 1        writing          f35150141e5f4058ac5a714e831e742e                0 multipart **Not Found**
mp-no-parts                     : 1        writing          c19bfd6fd5cb437c96ec2a8448f8b89d                0 multipart **No Entry**
nm                              : 1        active           a5ea55aeabab4fc194ff043d813ca159             2852 normal    Found
```

### CODE REVIEW

**Comment by kuenishi** [comment]
A simple run gave me this result:

``` sh
$ dev/dev1/bin/riak-cs escript ~/cs-2.1/riak_cs/priv/tools/internal/riak_cs_inspector.erl -p 10017 block list aaa a e07282b3c36f4ed7905a45f090a8bdf7
/home/kuenishi/cs-2.1/riak_cs/priv/tools/internal/riak_cs_inspector.erl:693: Warning: variable 'PartUUID' is unused
Connecting to localhost:10017...
Blocks in object [a/e07282b3c36f4ed7905a45f090a8bdf7]:
UUID =========================== Seq ==== Size ===== Value(first 8 or 32 bytes) =====================================
e07282b3c36f4ed7905a45f090a8bdf7        0          2                                                        <<97,10>>

```

**Comment by kuenishi** [comment]
It works fine, but I'd like that warning removed.

**Comment by ksauzz** [comment]
Oops, Updated.

**Comment by ksauzz** [comment]
@borshop merge

**Pull request merged**
