### PR TITLE
Fix riak-cs-ee build on debian

### PR DESCRIPTION
**Pull request by jaredmorrow**
## Description

During build of debian packages, the environment is cleaned by debuild
by setting all environmental variables to "".  This fact made the
passing of RIAK_CS_EE_DEPS variable work on accident until the `[]->false`
pattern was added to the rebar.config.script.  Though adding that
pattern fixed the OSS build, it did break debian package builds.

This commit fixes this by removing that check, but also not
automatically exporting the RIAK_CS_EE_DEPS makefile since an export
will export an empty variable and the rebar.config.script can now
trigger on an empty setting again.

Calling `unset RIAK_CS_EE_DEPS` is the only way to build an OSS
build after previously exporting the variable for riak-cs-ee.

In addtion a flag is passed into the debian's debuild so when
it RIAK_CS_EE_DEPS is available even when the environment is cleaned.
## Testing

Testing this is really annoying, so I did it myself and recorded my steps if anyone wants to sanity check.
### Case of unset variable

```
$ unset RIAK_CS_EE_DEPS
$ env | grep RIAK_CS_EE_DEPS

# Confirm rebar works w/o make
$ ./rebar get-deps
Building riak-cs
==> rel (get-deps)
==> riak_cs (get-deps)
<snip>

# Confirm same with make
$ make deps
Building riak-cs
==> rel (get-deps)
==> riak_cs (get-deps)

# Confirm package does not build EE version
$ make dist
Building riak-cs
<snip>
tar -C package -czf package/riak-cs-1.4.1.7.g9299226.tar.gz riak-cs-1.4.1.7.g9299226
cp package/riak-cs-1.4.1.7.g9299226.tar.gz .
# confirm make didn't add a variable and cause submake to build EE
$ diff pkg.vars.config package/riak-cs-1.4.1.7.g9299226/pkg.vars.config
$ grep package_name pkg.vars.config
{package_name, "riak-cs"}.
$ tar -tzf package/riak-cs-1.4.1.7.g9299226.tar.gz | grep riak_repl
```
### Case of set variable

```
$ export RIAK_CS_EE_DEPS=true
$ env | grep RIAK_CS_EE_DEPS
RIAK_CS_EE_DEPS=true
$ ./rebar get-deps
Building riak-cs-ee
==> rel (get-deps)
==> riak_cs (get-deps)
<snip>
$ make dist
Building riak-cs-ee
==> rel (get-deps)
==> riak_cs (get-deps)
<snip>
tar -C package -czf package/riak-cs-1.4.1.7.g9299226.tar.gz riak-cs-1.4.1.7.g9299226
cp package/riak-cs-1.4.1.7.g9299226.tar.gz .
$ diff pkg.vars.config package/riak-cs-1.4.1.7.g9299226/pkg.vars.config
$ grep package_name pkg.vars.config
{package_name, "riak-cs-ee"}.
$ tar -tzf package/riak-cs-1.4.1.7.g9299226.tar.gz| grep riak_repl
<snip>
riak-cs-1.4.1.7.g9299226/deps/riak_repl_pb_api/src/riak_repl_pb_api.app.src
riak-cs-1.4.1.7.g9299226/deps/riak_repl_pb_api/src/riak_repl_pb_api.erl
riak-cs-1.4.1.7.g9299226/deps/riak_repl_pb_api/priv/vsn.git

```
#### Testing package on Ubuntu

```
$ git checkout bugfix/jem-debian-missing-repl-cs-ee
Branch bugfix/jem-debian-missing-repl-cs-ee set up to track remote branch bugfix/jem-debian-missing-repl-cs-ee from origin.
Switched to a new branch 'bugfix/jem-debian-missing-repl-cs-ee'
$ uname -a
Linux build-ubuntu-1204-64 3.2.0-40-generic #64-Ubuntu SMP Mon Mar 25 21:22:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
$ env | grep RIAK_CS_EE_DEPS
$ export RIAK_CS_EE_DEPS=true
$ env | grep RIAK_CS_EE_DEPS
RIAK_CS_EE_DEPS=true
$ make package
Building riak-cs-ee
==> rel (get-deps)
==> riak_cs (get-deps)
<snip>
$ dpkg-deb -c package/packages/riak-cs-ee_1.4.1.10.g028bb83-1_amd64.deb | grep riak_repl
<snip>
-rw-r--r-- root/root      7532 2013-10-03 16:51 ./usr/lib/riak-cs/lib/riak_repl_pb_api-0.2.3/ebin/riak_repl_pb_api.beam
-rw-r--r-- root/root       255 2013-10-03 16:51 ./usr/lib/riak-cs/lib/riak_repl_pb_api-0.2.3/ebin/riak_repl_pb_api.app
-rw-r--r-- root/root     12520 2013-10-03 16:51 ./usr/lib/riak-cs/lib/riak_repl_pb_api-0.2.3/ebin/riak_repl_pb.beam
drwxr-xr-x root/root         0 2013-10-03 16:51 ./usr/lib/riak-cs/lib/riak_repl_pb_api-0.2.3/include/
-rw-r--r-- root/root       690 2013-10-03 16:51 ./usr/lib/riak-cs/lib/riak_repl_pb_api-0.2.3/include/riak_repl_pb.hrl
```
### Case of empty variable, but set (should act same as set variable)

```
$ export RIAK_CS_EE_DEPS=
$ env | grep RIAK_CS_EE_DEPS
RIAK_CS_EE_DEPS=
$ ./rebar get-deps
Building riak-cs-ee
==> rel (get-deps)
==> riak_cs (get-deps)
<snip>
$ make deps
Building riak-cs-ee
==> rel (get-deps)
<snip>
```

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Depends on https://github.com/basho/node_package/commit/589c384e8043e6c36c2c3646103892f45ed10daa which was added to node_package tag 1.3.8

**Comment by jaredmorrow** [comment]
The package build can be confirmed by searching the 'make package' stdio logs on build 14 of each platform here: http://goo.gl/WJDUa8 (must be on VPN).  I checked, all of them included "Building riak-cs-ee" and "riak_repl"

**Comment by jaredmorrow** [comment]
Similarly, to confirm this doesn't accidentally add riak_repl to non-cs-ee builds, here is a riak-cs build of the same branch http://goo.gl/UY1Kdi

**Comment by kellymclaughlin** [comment]
My tests verified your results. :+1:

**Comment by jaredmorrow** [comment]
Woohoo, thanks @kellymclaughlin

**Pull request merged**
