### PR TITLE
Make a PR without an extra Issue

### PR DESCRIPTION
**Pull request by cmeiklejohn**
It can be a little confusing to have two cards in the Kanban, one for the Issue, and one for the PR that solved the issue.  Github automatically makes an issue for each PR, but it looks like the "hub" helper script has a chance of getting around this.  Try it out.

### CODE REVIEW

**Comment by beerriot** [comment]
Looks like this is pretty simple.  Just

```
hub pull-request -i 182
```

and it automatically converts issues/182 into pull/182, right @cmeiklejohn?  Hub comes from https://github.com/defunkt/hub, though you have to check it out and use the `api-v3` branch right now, because Github has disabled the token auth that master uses.

**Comment by cmeiklejohn** [comment]
That's correct.  Also, according to the docs, you should be able to associate an already-open pull with an issue by switching to the branch with the open pull and running that command as well, but we haven't tested that one yet.

**Comment by beerriot** [comment]
Cool.  I think we can close this PR out then, unless you want to experiment more.

**Comment by beerriot** [comment]
@Vagabond also just pointed out that we can do this from the kanban board, using the `pull-request` link on the bottom of the ticket (next to the `ready-to-pull` button)

**Pull request closed without merging**
