### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by kuenishi**
- take off preview from put copy
- add Delete Multiple Objects

### CODE REVIEW

**Comment by kuenishi** [comment]
CC: https://github.com/basho/stanchion/pull/83

**Comment by shino** [comment]
> Syslog support through lager_syslog riak_cs/#617

This was added at 1.4.0 https://github.com/basho/riak_cs/commit/ab3c224dbeb9bc3eb9de9c928985738caa7d5eeb

**Comment by shino** [comment]
> A new command riak-cs-debug which retrieves diagnosis info including cluster-info

riak-cs-debug gathers information but does not diagnose by itself, does it?

**Comment by shino** [comment]
> Add a command riak-cs-stanchion to switch Stanchion IP and port manually

`riak-cs-admin stanchion` is better.

**Comment by shino** [comment]
> Add option to allow a delay for the initial GC collection

"collection" is duplicated

**Comment by shino** [comment]
> fold_objects made default in Riak CS

For release note, the full name `fold_objects_for_list_keys` is appropriate.

**Comment by shino** [comment]
> Unaborted or incomplete multipart uploads

I don't know the word "unaborted". Does it mean not-aborted?
I found an entry in Wikitionary [1] and it says "undo an abortion".
This meaning is different from "not yet aborted".

[1] http://en.wiktionary.org/wiki/unabort

**Comment by shino** [comment]
There are some merge commits/PRs which are bugs or affect users:
- 3908ed6 Merge pull request #915 from basho/feature/manifest-many-sinblings-warning
- a5cfaa5 Merge pull request #733 from basho/bugfix/jem-solaris-runner-fix
- 4355091 Merge branch 'bugfix/oos-user-creation' into develop
  [PR: https://github.com/basho/riak_cs/pull/666]
- 1df430e Merge pull request #636 from basho/jrd-max-ports

**Comment by shino** [comment]
Seems nice :smile: 
I added tiny fixes at 245de19 . With the change, :+1: from me.
If you are OK with it, please +1 and let's merge.

**Comment by shino** [comment]
@borshop merge

**Pull request merged**
