### PR TITLE
Add riak_test of GET with Range header

### PR DESCRIPTION
**Pull request by shino**

### CODE REVIEW

**Comment by shino** [comment]
This PR requires https://github.com/basho/erlcloud/pull/8

**Comment by shino** [comment]
@kellymclaughlin Sorry. I only added basic test cases. Range get needs more test cases.
I will rebase to the current release/1.3 branch and add some tests now.

**Comment by shino** [comment]
Rebased the branch and added necessary test cases.
Ready to be reviewed now.

**Comment by kellymclaughlin** [comment]
Looks good! +1 to merge.

**Comment by shino** [comment]
Merged #438

**Pull request merged**
