### PR TITLE
Simplify the JSON documents exchanged between riak_cs and stanchion.

### PR DESCRIPTION
**Pull request by kellymclaughlin**
User a simpler and more suitable JSON representation for exchanging user and bucket information.
## Testing

Ensure that user creation and bucket creation and deletion work as expected with the `s182-data-interchange-streamline` branches of `riak_cs` and `stanchion`.

This change also depends on [this](https://github.com/basho/stanchion/pull/9) accompanying pr in the stanchion repo.

### CODE REVIEW

**Comment by reiddraper** [comment]
It looks like there are some permissions issues with this branch:

```
# create a new user,
➜  Desktop  s3cmd mb s3://abc
Bucket 's3://abc/' created
➜  Desktop  s3cmd info s3://abc
ERROR: Access to bucket 'abc' was denied
```

and

```
➜  Desktop  s3cmd put ~/Downloads/googlechrome.dmg s3://abc/c 
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
/Users/reid/Downloads/googlechrome.dmg -> s3://abc/c  [1 of 1]
   147456 of 40737939     0% in    0s    23.05 MB/s  failed
WARNING: Upload failed: /c ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
^CSee ya!
```

**Comment by kellymclaughlin** [comment]
Check out the s182 stanchion branch in your riak_moss reps as well and that should resolve the issue.

**Comment by reiddraper** [comment]
Dope. Works now. Thanks

**Comment by reiddraper** [comment]
+1 to merge

**Pull request closed without merging**
