### PR TITLE
Bugfix/remove error log of anonymous access

### PR DESCRIPTION
**Pull request by shino**
Original issue #876 
- Removed `no_user_key` error log 152793b
- Changed handling of `undefind` for user key to avoid error messages like
  `Retrieval of user record for [] failed. Reason: <<"Key cannot be zero-length">>' .
  These logs happened when access admin resources`/riak-cs/users`as anonymous
  with configuration`{admin_auth_enabled, false}`.

### CODE REVIEW

**Comment by kuenishi** [comment]
When backing Riak is down, just curling to CS and getting via s3cmd differ in logs and return status: is that an another issue?

## Curl

```
> curl http://localhost:8080/kuenishi.test/start_mydev.sh                                                              
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request</body></html>
```

console.log

```
2014-06-12 13:52:30.861 [error] <0.122.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,["/buckets/kuenishi.test/objects/start_mydev.sh",{error,{case_clause,{error,disconnected}},[{riak_cs_wm_utils,ensure_doc,2,[{file,"src/riak_cs_wm_utils.erl"},{line,262}]},{riak_cs_wm_object,authorize,2,[{file,"src/riak_cs_wm_object.erl"},{line,65}]},{riak_cs_wm_common,authorize,2,[{file,"src/riak_cs_wm_common.erl"},{line,403}]},{riak_cs_wm_common,forbidden,2,[{file,"src/riak_cs_wm_common.erl"},{line,177}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resou..."},...]},...]},...]},...}}
```

## s3cmd

```
> s3cmd -c local.s3cfg get s3://kuenishi.test/blanc -                                                                  
s3://kuenishi.test/blanc -> <stdout>  [1 of 1]
ERROR: S3 error: 403 (Forbidden): 
```

console.log:

```
2014-06-12 13:53:02.024 [error] <0.551.0>@riak_cs_wm_common:maybe_create_user:222 Retrieval of user record for s3 failed. Reason: disconnected
```

**Comment by kuenishi** [comment]
Also, I'm not sure is this a valid behaviour: using unknown user key;

``` sh
> head -n 5 local.s3cfg                                                                                                
[default]

## access_key = J_PJJS7NEHXJSQQV5XJH
access_key = henry8
secret_key = rktX1Hy4VX3V0Favo3bncONnfUG7gcuEUqV40A==
> s3cmd -c local.s3cfg get s3://kuenishi.test/blanc -
s3://kuenishi.test/blanc -> <stdout>  [1 of 1]
ERROR: S3 error: 403 (Forbidden): 
```

And the log says disconnected:

```
2014-06-12 13:59:15.520 [error] <0.2559.0>@riak_cs_wm_common:maybe_create_user:222 Retrieval of user record for s3 failed. Reason: disconnected
```

This would be the real case for `no_user_key`, isn't it?

**Comment by kuenishi** [comment]
So, for now I'm -1 on this pull request as the log is misleading. I don't think we should remove `no_user_key` completely.

**Comment by shino** [comment]
> curl http://localhost:8080/kuenishi.test/start_mydev.sh  

Hmm, I didn't test no Host headers that does not match `cs_root_host`.
Seems like another issue but I will investigate it later.

> using unknown user key;

`no_user_key` is the case that no user key is specified. Unknown user is another case.

**Comment by shino** [comment]
One more question: the two behaviors above you mentioned are different from develop?

**Comment by kuenishi** [comment]
+1 f11d079
Okay, my bad. I understood `no_user_key` was about request header, not on Riak. I'll test them against the new develop and open another issue.

**Comment by shino** [comment]
@borshop merge

**Pull request merged**
