### PR TITLE
Make logging in bucket listing map function lager version agnostic

### PR DESCRIPTION
**Pull request by kellymclaughlin**
The parse transform for lager changed between lager 1.2.X and lager 2.0.0.
This causes problems listing the contents of buckets when using Riak CS 1.4 or
later with older versions of Riak because the map_keys_and_manifests function
is run on Riak nodes as part of a MapReduce job. That function contains a
lager call that is rewritten to use a lager module that did not exist in
versions prior to 2.0.0 and when run on Riak nodes that still uses an earlier
lager version it can result in errors. The errors happen when the bucket that
a list operation is run against contains a deleted object. This commit changes
the lager call in the map_keys_and_manifests function to use a call that is
not transformed and is safe for older Riak versions as well as the 1.4.X
releases.

### CODE REVIEW

**Comment by reiddraper** [comment]
Thoughts on going ahead and including the BKey here too now?

**Comment by kellymclaughlin** [comment]
> Thoughts on going ahead and including the BKey here too now?

Added in [7951351](https://github.com/basho/riak_cs/commit/79513518a10992f72b414dea46c2977b2f2c525a)

**Comment by reiddraper** [comment]
- [x] Test with Riak 1.4.2
- [x] Test with Riak 1.3.x

**Comment by reiddraper** [comment]
I'm kind of on the fence about whether this should be a warning or an error. I'm inclined to say error, since it affects how many keys are returned in list keys.

**Comment by reiddraper** [comment]
Confirmed this new commands works with both versions of lager. Woot.

**Comment by reiddraper** [comment]
+1

**Pull request merged**
