### PR TITLE
Riak client abstraction layer for bag support

### PR DESCRIPTION
**Pull request by shino**
Instead of using `riakc_pb_socket` directly, add `riak_cs_riak_client` that understands CS specific types like users and buckets. `riak_cs_riak_client` wraps one or more `riakc_pb_socket` processes. All Webmachine resource callbacks and gc/access daemons use them. 

This PR includes also:
- multibag support (this is motivation for introducing `riak_cs_riak_client`)
- bug fix of premature connection release ba13361

### CODE REVIEW

**Comment by reiddraper** [comment]
Is this necessary for the multi-cluster work? Is that why we're trying to target it for 1.5?

**Comment by shino** [comment]
Yes. This started as a refactoring work of #853. (maybe it seems like a rewrite?)

**Comment by shino** [comment]
Rebased one #874 
For reviewers, please pick either one :) Then I will close another one.

**Comment by shino** [comment]
Close in favor of #874

**Pull request closed without merging**
