### PR TITLE
capitalization of x-amz-meta- header on multipart upload.

### PR DESCRIPTION
**Pull request by shino**
I uploaded file with x-amz-meta- header on multipart upload. But the stored meta data was capitalised.
- putting meta: x-amz-meta-hoge:text
- stored meta: X-Amz-Meta-Hoge: text
## uploading file with MP

```
% s3cmd -c ~/Desktop/kk.cfg --add-header=x-amz-meta-hoge:text put VisualVM_135.dmg s3://test2
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
VisualVM_135.dmg -> s3://test2/VisualVM_135.dmg  [part 1 of 2, 15MB]
 15728640 of 15728640   100% in   33s   459.32 kB/s  done
VisualVM_135.dmg -> s3://test2/VisualVM_135.dmg  [part 2 of 2, 5MB]
 5890107 of 5890107   100% in   12s   456.68 kB/s  done
```
## tcpdump on the uploading

```
12:00:16.312 192.168.11.7:56360 -> xxx.xxx.xxx.xxx:8080 #1 HTTP 1.1 request: POST http://test2.s3.amazonaws.com/VisualVM_135.dmg?uploads
    Host: test2.s3.amazonaws.com
    Accept-Encoding: identity
    x-amz-meta-hoge: text
    content-length: 0
    content-type: application/octet-stream
    Authorization: AWS KTBG_FWRVG_SSK02MMP3:mPtrBDJZNpsMhLCPP3v7f1CJM+Q=
    x-amz-date: Fri, 22 Mar 2013 03:00:16 +0000
```
## getting uploaded file.

```
% s3curl.pl --id kk   -- -v -x xxx.xxx.xxx.xxx:8080 -X HEAD http://test2.s3.amazonaws.com/VisualVM_135.dmg
* About to connect() to proxy xxx.xxx.xxx.xxx port 8080 (#0)
*   Trying xxx.xxx.xxx.xxx...
* connected
* Connected to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx) port 8080 (#0)
> HEAD http://test2.s3.amazonaws.com/VisualVM_135.dmg HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
> Host: test2.s3.amazonaws.com
> Accept: */*
> Proxy-Connection: Keep-Alive
> Date: Fri, 22 Mar 2013 03:01:10 GMT
> Authorization: AWS KTBG_FWRVG_SSK02MMP3:2clrTjGX9d0HImwicmbgSVjyfmg=
>
< HTTP/1.1 200 OK
< X-Amz-Meta-Hoge: text
< Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
< Last-Modified: Fri, 22 Mar 2013 03:00:16 GMT
< ETag: "c77f589597f345cfa806289252cf1156"
< Date: Fri, 22 Mar 2013 03:01:10 GMT
< Content-Type: application/octet-stream
< Content-Length: 21618747
```

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
These changes look good and the unit tests, client tests, and `riak_test` tests all pass. Dialyzer output is clean. My only request is could you write a test for `extract_user_metadata`? An `eunit` test or `eqc` property would suffice.

**Comment by shino** [comment]
Good point. It's my fault to miss tests.
I added simple put/get tests.
But I want to add one more test of zero-length PUT copy test case in this PR.
Please wait a little more.

**Comment by shino** [comment]
Added PUT copy test case with a little source modification.
Would you please review it again?

**Comment by kellymclaughlin** [comment]
Re-ran all tests and dialyzer. All looks good. +1 to merge.

**Pull request merged**
