### PR TITLE
Handle tombstones in manifest fsm

### PR DESCRIPTION
**Pull request by kellymclaughlin**
```
(riak-cs@127.0.0.1)36> 17:41:04.327 [error] gen_fsm <0.17924.129> in state waiting_command terminated with reason: bad argument in call to erlang:binary_to_term(<<>>) in lists:map/2 line 1173
```

### CODE REVIEW

**Comment by slfritchie** [comment]
+1 to merge, thanks!

**Comment by shino** [comment]
@kellymclaughlin May I ask a question for this old issue?

I don't understand why empty binary check at https://github.com/basho/riak_cs/pull/252/files#L1R446 is added.
Does not `dict:is_key(<<"X-Riak-Deleted">>, MD)` suffice in order to confirm an object is in tombstone state?
I want to understand the change to fix the issue https://github.com/basho/riak_cs/issues/524.

**Comment by kellymclaughlin** [comment]
I believe the reason is that the `X-Riak-Deleted` has not always been reliably included so the extra check is to handle those cases. I think that problem has since been corrected so we can probably look at only using the check for `X-Riak-Deleted` in the future.

**Comment by shino** [comment]
@kellymclaughlin Thanks for reply. I understand it as a historical reason.

**Pull request closed without merging**
