### PR TITLE
Update riak_test modules for new riak_test api

### PR DESCRIPTION
**Pull request by kellymclaughlin**

### CODE REVIEW

**Comment by andrewjstone** [comment]
I'm seeing the following failure: 

```
10:37:11.516 [info] Wait until ring converged on ['dev1@127.0.0.1','dev2@127.0.0.1','dev3@127.0.0.1','dev4@127.0.0.1']
10:38:37.031 [error] Expected 'Res 0', got: Res 2

10:38:37.042 [warning] external_client_tests failed: {fail,[{external_client_tests,confirm,0,[{file,"riak_test/tests/external_client_tests.erl"},{line,37}]}]}
10:38:37.042 [error] Error in process <0.155.0> on node 'riak_test@127.0.0.1' with exit value: {fail,[{external_client_tests,confirm,0,[{file,"riak_test/tests/external_client_tests.erl"},{line,37}]}]}


10:38:37.043 [error]
================ external_client_tests failure stack trace =====================
{fail,[{external_client_tests,confirm,0,
                              [{file,"riak_test/tests/external_client_tests.erl"},
                               {line,37}]}]}
================================================================================

10:38:37.043 [notice] external_client_tests Test Run Complete

Test Results:
external_client_tests-riak_cs_kv_multi_backend,riak_kv_bitcask_backend: fail
---------------------------------------------
1 Tests Failed
0 Tests Passed
That's 0.0% for those keeping score
```

**Comment by kellymclaughlin** [comment]
I was having environment issues with the php tests. Do you mind removing `test-php` from the `test-client` Makefile target and trying again?

**Comment by andrewjstone** [comment]
@kellymclaughlin That worked. However, don't we need those PHP tests to pass?

**Comment by kellymclaughlin** [comment]
Yeah, i'll investigate it further

**Comment by andrewjstone** [comment]
:+1:

**Pull request closed without merging**
