### PR TITLE
[DO NOT MERGE] Force re-creation of PLT for OTP library

### PR DESCRIPTION
**Pull request by shino**
PLEASE DO NOT MERGE.
This is a DUMMY PR, only for cleaning up the PLT file.

cf. https://github.com/basho/riak_cs/pull/848#issuecomment-42474222

### CODE REVIEW

**Comment by shino** [comment]
Please `+1 83cea22` on this PR if you need to cleanup PLT again :smile:

**Comment by ksauzz** [comment]
:+1: 83cea22

**Comment by kuenishi** [comment]
+1 83cea22

**Comment by shino** [comment]
Obsolete. Close.

(internal note: If PLTs go wrong, rebuild from `test-riak_cs #1018`)

**Pull request closed without merging**
