### PR TITLE
Increase request pool size on external client tests [JIRA: RCS-280]

### PR DESCRIPTION
**Pull request by ksauzz**
This PR has 2 changes:
- Improve rtcs:setup/x to merge specified prams into default prams
- Increase request_pool size on external client tests

Sometimes request pool workers of poolboy is exhausted on external_client_tests, then it causes the
test fails, since external_client_tests runs individual client tests concurrently using 'make -j 8'.
So pool size should be increased enough.
I changed rtcs:setup to merge specified params into default configs before Increasing pool size, to do it easily.

### CODE REVIEW

**Comment by kuenishi** [comment]
The reason why we had small connection pools by default is to find bugs by setting more tight parameters. If it's an issue in specific test, the parameters should be specified in each test setup, external_client_tests for this case.

**Comment by kuenishi** [comment]
Fm, I was wrong ^^;

**Comment by ksauzz** [comment]
ha, my 3rd line in the description was unclear. Updated.

**Comment by shino** [comment]
Simpler API than before. Nice change :smile:

**Comment by shino** [comment]
+1 14c47a1

**Comment by shino** [comment]
@borshop merge

**Comment by kuenishi** [comment]
No release note needed as this is a test code update

**Pull request merged**
