### PR TITLE
tools.mk makefile and dialyzer fixes

### PR DESCRIPTION
**Pull request by reiddraper**
_DO NOT MERGE_

Just starting a conversation with this for now. Using the new dialyzer options from `tools.mk` has eliminated most of the dialyzer warnings, as the dependencies are now just included in the PLT, instead of being passed to the dialyzer command itself. There were a couple of long-standing 'appeasing dialyzer' pieces of code that I've removed now. I'm of the mind that 'if the test passes', they should be ok. But it's worth going through them with a fine-tooth comb.

### CODE REVIEW

**Comment by reiddraper** [comment]
I'm seeing two r_t failures with this branch, twice in a row too, so probably legit. The `access_stats_test` and `cs743_regression_test`. Will make sure they're passing on develop too.

**Comment by kuenishi** [comment]
Those tests are for bugs only fixed in release/1.4 branch, not in develop. Probably make clean-riak-tests might remove those test beam files. Or merging release/1.4 will solve the problems.

**Comment by reiddraper** [comment]
Aha! I'll try that and re-run. Thanks.

**Comment by reiddraper** [comment]
After running `clean-riak-test` and recompiling the riak_test code:

```
0 Tests Failed
16 Tests Passed
That's 100.0% for those keeping score
```

**Comment by reiddraper** [comment]
Alright, when someone gets a chance, I'd appreciate a 'full-review' on this. If it goes in, I'd like for it to merged before #631, and to rebase #631 against this. Not that it matters too much which order they go in.

**Comment by kuenishi** [comment]
quick result:
- eunit: `make test` didn't passed for me, ~~looks like you just forgot modifying eunit tests.~~ it was me who didn't remove .eunit. now it passed. https://gist.github.com/kuenishi/8571333#file-eqc
- xref: got following warnings without RIAK_CS_EE_DEPS, is this expected? With RIAK_CS_EE_DEPS it worked fine.

```
./rebar xref skip_deps=true | grep -v unused | egrep -v -f ./xref.ignore-warnings
Building riak-cs
==> riak_cs (xref)
src/riak_cs_block_server.erl:337: Warning: riak_cs_block_server:get_block_remote/5 calls undefined function riak_repl_pb_api:get/5 (Xref)
src/riak_cs_block_server.erl:348: Warning: riak_cs_block_server:normal_nval_block_get/8 calls undefined function riak_repl_pb_api:get/5 (Xref)
src/riak_cs_config.erl:194: Warning: riak_cs_config:maybe_get_cluster_id/3 calls undefined function riak_repl_pb_api:get_clusterid/2 (Xref)
ERROR: xref failed while processing /home/kuenishi/src/riak_cs: rebar_abort
```
- dialyzer: ~~make -f tools.mk dialyzer didn't work for me because I don't have .riak_combo_dialyzer_plt~~

```
$ make -f tools.mk dialyzer
make: *** No rule to make target `compile', needed by `/home/kuenishi/.riak_combo_dialyzer_plt'.  Stop.
```

but it worked with `make -f tools.mk -f Makefile dialyzer`: https://gist.github.com/kuenishi/8571333#file-dialyzer-L8 ~~
and looks like we found undef function call!

**Comment by kuenishi** [comment]
Correction: dialyzer worked as advertized.

**Comment by kuenishi** [comment]
- [x] riak_test
- [x] eunit
- [x] xref
- [x] dialyzer
- [x] code review: no notable change in code

**Comment by kuenishi** [comment]
+1

**Comment by reiddraper** [comment]
thanks!

**Pull request merged**
