### PR TITLE
Change admin.{ip|port} => admin.listener [JIRA: RCS-142]

### PR DESCRIPTION
**Pull request by kuenishi**
Follow up of https://github.com/basho/riak_cs/pull/1082#discussion_r26013665 . I believe this is the last one for code freeze.

### CODE REVIEW

**Comment by shino** [comment]
Diff looks nice. riak_test'ing...

**Comment by Basho-JIRA** [comment]
Already nicely written at https://github.com/basho/riak_cs/blob/develop/RELEASE-NOTES.md#backend-configuration 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by kuenishi** [comment]
Wrongly closed by JURA ...

**Comment by shino** [comment]
@borshop merge

**Pull request merged**
