### PR TITLE
Configuration option to control user creation

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Add configuration option to allow system installers to choose to restrict user creation to admins or permit anyone to create a user directly.

The configuration option, `anonymous_user_creation`, can be placed in the `riak_moss` section of the app.config. The default value is `false` is no value is specified.
## Testing

With `anonymous_user_creation` set to `true`, user creation should behave as it always has up to this point. Any user should be able to issue a POST request using curl with no authentication required.

With `anonymous_user_creation` set to `false`, anonymous POST requests to `/riak-cs/user` should result in a `403` error. Authenticated POST requests from non-admin user accounts should also receive a `403` in response. Finally, only a POST request from the admin user account should be successful in creating the new user account. 

Using _s3curl_ a simple way to issue the POST would look as follows:

```
s3curl --id cs --post newuser.json --contentType application/json -- --proxy1.0 "localhost:8080" -v http://s3.amazonaws.com/riak-cs/user
```

where _newuser.json_ contains the following:

```
{"email":"test1@test.com", "name":"test1"}
```

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@kellymclaughlin I know it's really awful, but could this support PUT as well?  This would allow you to create users with s3cmd and the like.  Yes, it's gross, I know.  Thoughts?

**Comment by kellymclaughlin** [comment]
It is pretty awful, but it would be a pretty minor change to make it work. If you think it would be very useful I can add that in.

**Comment by cmeiklejohn** [comment]
@kellymclaughlin I'm going to turn the anonymous creation on for now to keep moving forward, but let's plan to mumble about it on Monday.

**Comment by cmeiklejohn** [comment]
+1, other than the aforementioned objection.

**Comment by cmeiklejohn** [comment]
+1 merge it!

**Pull request merged**
