### PR TITLE
Bugfix/eqc process leak

### PR DESCRIPTION
**Pull request by shino**
Fix process leak found in #761 
- Stop riak_cs_get_fsm and riak_cs_dummy_reader processes after single command sequence
- Refactoring

Increasing beam.smp's memory size can be seen by, for instance:

```
$ ./rebar eunit skip_deps=true compile_only=true && \
    ERL_LIBS=$ERL_LIBS:deps erl -pa .eunit
> spawn(fun() -> riak_cs_get_fsm_eqc:test(1000) end).
```

### CODE REVIEW

**Comment by reiddraper** [comment]
I'm not able to see any leaking processes, seen via: `length(erlang:processes())`. Once the test has been run once, it stays at 60 processes, with and without this change. Am I missing something?

**Comment by shino** [comment]
The word "leak" may be misleading, sorry.
Number of processes continue to grow while test _is running_.

I found growth of memory (RES) of beam.smp and process count when doing:

```
> spawn(fun() -> riak_cs_get_fsm_eqc:test(1000) end).
```

If your machine has more RAM, 2000 or 3000 tests might make the situation more obvious instead of 1000.
In my environment (Linux with 8GB RAM), 1000 tests was sufficient that OOMKiller killed beam.smp
when it reached to about 5GB RES :P

**Comment by reiddraper** [comment]
Aha! Yes, I see that now. And the branch does fix it. I'll take a look at the test refactoring next.

**Comment by reiddraper** [comment]
Great work, :+1:

**Pull request merged**
