### PR TITLE
User creation fails when just ~10 users created

### PR DESCRIPTION
**Pull request by kuenishi**
This pull request just includes the test that reproduces the bug, for reporting. Right fix of code and tests will follow.

Fail log: https://gist.github.com/kuenishi/cf174e2bf3d796fcc378

### CODE REVIEW

**Comment by shino** [comment]
Is this a bug of test code or of source code?

**Comment by kuenishi** [comment]
I still don't know. Needs investigation.

**Comment by ksauzz** [comment]
According the fail log, the test failed at line 41. That means admin user test failed before running 10 users test.

**Comment by shino** [comment]
Could not reproduce.

**Pull request closed without merging**
