### PR TITLE
Add helper fun to handle non bools in dtrace returns

### PR DESCRIPTION
**Pull request by reiddraper**
- Add comment about rationale behind some HTTP status codes

Tested by either trying to upload a > 5GB file, or setting the default max content length to something like 1MB.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
This looks good, but I'm going to attempt to expand our riak_test module for mp uploads to test this.

**Comment by kellymclaughlin** [comment]
+1 on this from me. Merge away once taking a look at my riak_test additions.

**Comment by kellymclaughlin** [comment]
I've merged the riak_test refactoring now so probably should rebase this from `release/1.3` prior to merging to address any conflicts and update the expected return from `rtcs:setup` in the new test module. Happy to do that after you take a look.

**Comment by reiddraper** [comment]
+1

> Happy to do that after you take a look.

Yeah, if you don't mind going through the rebase conflicts, I'd appreciate it.

**Comment by kellymclaughlin** [comment]
Rebased and resolved all conflicts. All the `riak_test` modules are passing. So I think it's ready to merge if you're ok with it.

**Comment by reiddraper** [comment]
+1 to merge

**Pull request merged**
