### PR TITLE
Pin Multibag and node_package

### PR DESCRIPTION
**Pull request by kuenishi**

### CODE REVIEW

**Comment by russelldb** [comment]
LGTM +1 a00b331

**Comment by kuenishi** [comment]
Thanks, @russelldb . But node_package 2.0.2 is now weird, so I removed it.

**Comment by russelldb** [comment]
+1 93c986f

I KNOW!

But this looks OK too

**Comment by kuenishi** [comment]
Come on, @borshop

**Comment by kuenishi** [comment]
Build #989 successfully finished. Merging.

**Pull request merged**
