### PR TITLE
Yessir riak client, part 1

### PR DESCRIPTION
**Pull request by shino**
YESSIR riak_client part 1

Communication with Riak KV is stubbed out almost completely.
Main purpose is to benchmark/optimize on-memory logic of riak_cs.

_Caution_ Communication with Stanchion is NOT stubbed out.
Stanchion and Riak KV is needed for create user operation, etc.
Also, bucket properties verification at riak-cs startup interacts
with Riak KV actually.

---

Setting in advanced.config:

```
  {riak_client, riak_cs_yessir_riak_client}
```

For user credential, secret should be user key id + "+Secret",
example for s3cfg:

```
access_key = MZ59BPUOELYZNPTEPFR3
secret_key = MZ59BPUOELYZNPTEPFR3+Secret
```

Current Status is as following, not-yet-implemented functionalities
will come with subsequent PRs (hopefully):
- [x] list buckets (only one bucket)
- [x] list object (only one entry)
- [x] get object (10-byte, fixed content)
- [ ] put object
- [ ] delete object
- [x] GC list keys (empty key list)
- [ ] GC (with some keys)
- [x] access/storage stats PUT
- [ ] access/storage GET

### CODE REVIEW

**Comment by slfritchie** [comment]
+1 I heartily approve of this hackery.

One idea might be to encode the object size in the S3 bucket name, e.g. the suffix is digits like "bucket4096" for objects with 4 Kbyte size?

**Comment by shino** [comment]
> One idea might be to encode the object size in the S3 bucket name, e.g. the suffix is digits like 
> "bucket4096" for objects with 4 Kbyte size? 

Must be implemented in subsequent PRs :+1:

**Comment by shino** [comment]
@borshop merge

**Comment by kuenishi** [comment]
You should not change any default config in advanced.config unless we have any other moderate choice.

**Comment by shino** [comment]
Sorry for that. The change was completely my mistake. 
It was removed in current develop.

**Pull request merged**
