### PR TITLE
clojure test fails: dependency error and NumberFormatException

### PR DESCRIPTION
**Pull request by shino**
Depends on https://github.com/reiddraper/clj-aws-s3/pull/1.

`make test-clojure` fails:

```
Could not find metadata org.codehaus.jackson:jackson-mapper-asl/maven-metadata.xml in local (/home/shino/.m2/repository)
Could not transfer metadata org.codehaus.jackson:jackson-mapper-asl/maven-metadata.xml from/to central (http://repo1.maven.org/maven2/): Checksum validation failed, expected c09b3634e82c52c906ef592e967ab609fbbcec62 but is 2a14c1a0b7c1ced8a9f78d8f68380ba3904829a2
Failure to find org.codehaus.jackson:jackson-mapper-asl/maven-metadata.xml in https://clojars.org/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced
This could be due to a typo in :dependencies or network issues.
Could not resolve dependencies
make: *** [test-clojure] Error 1
```

By updating AWS SDK to the latest (1.4.1), this error goes away and `lein deps` runs successfully, but no facts are found:

```
$ make test-clojure
No facts were checked. Is that what you wanted?
```

In REPL, a compiling error can be seen:

```
user=> (use 'java-s3-tests.core)
CompilerException java.lang.NumberFormatException: Invalid number: 2007-2013, compiling:(java_s3_tests/core.clj:3:24)
```

So change license comments from `comment` form to semicolons.

I don't familiar with Clojure/Leiningen, please tell me if there is better way or inappropriate change.

### CODE REVIEW

**Comment by reiddraper** [comment]
I pushed `clj-aws-s3` 0.4.1 with the changes from reiddraper/clj-aws-s3#1, and pushed a commit to this branch to use that dependency. I'm +1 to merge, but do you want to try my commit and double-check?

**Comment by shino** [comment]
Thank you for review and clj-aws-s3 works.
`make test-clojure` succeeds with your change.

I will merge right now.

**Comment by reiddraper** [comment]
woot!

**Comment by reiddraper** [comment]
ah, just realized this got merged into `release/1.3`, let's make sure to merge that back into develop

**Pull request merged**
