### PR TITLE
License headers

### PR DESCRIPTION
**Pull request by argv0**
Review suggestion:

for i in `git ls-files`; do open -W -a /Applications/Emacs.app/ $i; done

(-W waits for the app to exit)

### CODE REVIEW

**Comment by reiddraper** [comment]
Do we want to worry about doing this for the non-Erlang files too, like the python, clojure, etc. tests?

**Comment by kellymclaughlin** [comment]
I would think we probably should add them to the tests too.

**Comment by kuenishi** [comment]
OTP includes copyright notice in its tests.

https://github.com/erlang/otp/blob/maint/lib/kernel/test/code_a_test.erl

**Comment by kuenishi** [comment]
I rebased to the latest and add some headers and seems covered the whole source code (except bash scripts). Anything else to add header?

**Comment by kuenishi** [comment]
If nothing, +1 to merge

**Comment by kellymclaughlin** [comment]
+1

**Pull request merged**
