### PR TITLE
Add riak-cs-debug

### PR DESCRIPTION
**Pull request by ksauzz**
Add riak-cs-debug to gather information for troubleshooting. Most part of this is a copy of riak-debug.

gathering info:
- logs
  - access.log
  - console.log
  - error.log
  - crash.log
- configs
  - app.config
  - vm.args
- system command results
- riak  command results
  - riak-cs-gc status
  - riak-cs-storage status
  - riak-cs-cinfo

_This PR was extracted from #826._

### CODE REVIEW

**Comment by kuenishi** [comment]
```
> rel/riak-cs/bin/riak-cs-debug
...................EE........EEE.. /home/kuenishi/src/riak_cs/riak-cs@127.0.0.1-riak-cs-debug.tar.gz
```

Seems working correctly.

**Comment by kuenishi** [comment]
+1 c20c7c0

**Comment by ksauzz** [comment]
Thanks.

**Comment by ksauzz** [comment]
@borshop merge

**Pull request merged**
