### PR TITLE
Pre-signed URL query parameters are not handled properly

### PR DESCRIPTION
**Pull request by kellymclaughlin**
The query parameters of a pre-signed request are dropped by the s3 rewrite module and this causes authentication for any requests using this type of request to fail.

### CODE REVIEW

**Comment by shino** [comment]
GET by pre-auth URL works at least most URLs.
But I tried some times, one pre-auth URL failed by Access Denied.
The url includes`'%2B` = `+` in its URL:

```
curl -s -v -x 127.0.0.1:8080 'http://test.s3.amazonaws.com/1?AWSAccessKeyId=LAI24TWDUMJ525V1XWIR&Signature=2MD0Ku%2BGxRdOaA6QmQSyRHKRGkI%3D&Expires=1364496605'
```

Using redbug shows:

```
(riak-cs@127.0.0.1)7> redbug:start("riak_cs_s3_auth:'_' -> return", [{print_depth, 10}, {msgs, 100}]).
[snip]
11:18:35 <<0.4982.0>> {riak_cs_s3_auth,check_auth,
                          ["2MD0Ku GxRdOaA6QmQSyRHKRGkI=",
                           "2MD0Ku+GxRdOaA6QmQSyRHKRGkI="]}
[snip]
```

The url is created by erlcloud as:

```
Conf = erlcloud_s3:new("LAI24TWDUMJ525V1XWIR", "GVurV_VZfofcu9XuguB_Lv6NTp-u_4ecuZYgbA==").
{_, _, URI} = erlcloud_s3:make_link(10000, "test", "1", Conf).
```

Are there multiple decodings of URL??

**Comment by kellymclaughlin** [comment]
Nice catch @shino. I fixed the double decode problem and updated the test cases to check for that.

**Comment by shino** [comment]
still doubly decoded.
Little trial to encode back query parameters: https://github.com/basho/riak_cs/commit/7e96c77

**Comment by kellymclaughlin** [comment]
I did not realize that `wrq:get_qs_value` would also decode the query parameter values. [55660c5](https://github.com/basho/riak_cs/commit/55660c518c58c73d7e7d49fca5296bfa3bf633e5) I think completes the fix.

**Comment by shino** [comment]
It works! +1 to merge.

**Pull request merged**
