### PR TITLE
Update ceph/s3-tests to latest, modified to 1.5.0

### PR DESCRIPTION
**Pull request by kuenishi**
Addresses #880. But depends on #904 and #903 .
Changes from current tests is described [here](https://github.com/basho/s3-tests/compare/basho:master...riakcs-1.5).

### CODE REVIEW

**Comment by shino** [comment]
Could you shortly describe changes in basho/s3-tests?
Rebased on upstream master?

**Comment by kuenishi** [comment]
Yes, rebased and enabled several tests newly added at 1.5.0, such as delete multiple objects and copy.

**Comment by shino** [comment]
Rebased on `release/1.5` to incorporate changes in #903 and #904.

**Comment by shino** [comment]
@borshop merge

**Pull request merged**
