### PR TITLE
Bugfix/boto larger file upload tests

### PR DESCRIPTION
**Pull request by reiddraper**
Make sure to have `{enforce_multipart_part_size, false}` in your `app.config`. Run `make test-python` just as before. Take a look at the commit messages for details.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Not sure what I may be doing wrong here: https://gist.github.com/kellymclaughlin/6d79aaf799fe75d655b3

I have `{enforce_multipart_part_size, false}` set in my app.config. Any ideas?

**Comment by reiddraper** [comment]
Make sure you have `{cs_version` set too. Sorry that wasn't in the original description

**Comment by kellymclaughlin** [comment]
Ahh, yes. That was it thanks. This looks good. +1 to merge.

**Comment by reiddraper** [comment]
woot!

**Pull request merged**
