### PR TITLE
Remove EE and OSS differentiation. signature_v4 access via riak-cs.conf

### PR DESCRIPTION
**Pull request by Bob-The-Marauder**
Some parts commented rather than removed at this stage in case they later prove necessary.

### CODE REVIEW

**Comment by shino** [comment]
Some comments from old guy.
At first, I'm very happy to look at the new activity in this repo :smile:

This comment does not to intent two points below should be addressed
before merge, but just to notice some old issues/concerns.

1. `rebar.config.script` was just for OSS/EE deference. It can be removed completely
   if there is only one OSS flavor. `rebar.config` will just suffice.
2. v4 authentication is *NOT COMPLETED* yet.  The current status is not as secure as S3 is [1], and some API does not support v4 [2] [3].
   I agree to make it accessible from conf, but it may be better to include some "unfinished" caution in the `@doc`.

[1] https://github.com/basho/riak_cs/issues/1059
[2] https://github.com/basho/riak_cs/issues/1058
[3] https://github.com/basho/riak_cs/issues/1060

**Comment by Bob-The-Marauder** [comment]
I tried removing `rebar.config.script` but CS refused to make packages without it. Guessing it's a packaging issue. I will see if I can correct for that in future updates.
Thank you for the additional v4 comments. I have changed the comment in our internal copy of riak-cs.conf to "experimental support" and that will probably be reflected here sooner or later.

**Comment by shino** [comment]
Thanks for the update.

Just for the future change, a comment about rebar.config.script (my previous comment was insufficient, sorry).

It creates pkg.vars.config file for packaging. Because the file was different for OSS and EE versions, it was created dynamically. Now OSS version is the only one, the file can be static.
What should be done are:
- remove the line from .gitignore https://github.com/basho/riak_cs/blob/develop/.gitignore#L14, and
- add the file to git

Thanks again!

**Comment by shino** [comment]
Oops, I missed another thing the script does.

`git mv dialyzer.ignore-warnings.ee dialyzer.ignore-warnings` is needed.

**Comment by shino** [comment]
Looks nice!

**Comment by Bob-The-Marauder** [comment]
Thank you for your help. Looking to tag this as 2.1.2rc2

**Pull request merged**
