### PR TITLE
Feature/repl v3 test #648 rebased

### PR DESCRIPTION
**Pull request by kuenishi**
#648 have been long left, and it just works. So we'd better merge it than nothing until 1.5.0.

### CODE REVIEW

**Comment by kuenishi** [comment]
Test failure was because of timeout (1200 seconds) of long PLT build due to version change of OTP to R15. dializer in R15 is slow because it runs in single thread.

**Comment by kuenishi** [comment]
rebased to latest develop to include #873 .

**Comment by reiddraper** [comment]
@borshop merge

**Comment by bookshelfdave** [comment]
yay!

**Comment by shino** [comment]
Yay! Great work >  @metadave  @kuenishi and @reiddraper :exclamation:

**Pull request merged**
