### PR TITLE
Can't do multi-part uploads with query string authentication

### PR DESCRIPTION
**Pull request by kellymclaughlin**
When multi-part uploads and query string authentication are used together, Riak CS raises several different exceptions.

I want to upload some files with an AJAX client. To this end, I need to apply the multi-part upload and the query string authentication. However, I met some problems.

The first issue is the lack of CORS support. I fixed that by setting up nginx to reply to `OPTIONS` requests with the correct headers.

After that, when uploading with the `PUT` method, Riak CS replies with a 405 (Method not allowed) HTTP code with no additional message.
If I use the `POST` method, I get a 403 (Forbidden) HTTP code and "Access Denied" in the XML response.

I tried with both URL formats:
- /bucket/key?Signature=X&Expires=X&AWSAccessKeyId=X&uploadId=X&partNumber=X
- /bucket/key/uploads/uploadId?Signature=X&Expires=X&AWSAccessKeyId=X&partNumber=X

My script works well on Amazon S3 (with the first URL format) but fails on Riak CS 1.3.1 on Debian 64-bits.

### CODE REVIEW

**Comment by reiddraper** [comment]
> The first issue is the lack of CORS support. I fixed that by setting up nginx to reply to OPTIONS requests with the correct headers.

I've created #581 to track CORS support work.

**Comment by kellymclaughlin** [comment]
I have reproduced the authentication issue. I am working on a fix now and should have a pull request ready very shortly. Thanks for the report!

**Comment by kellymclaughlin** [comment]
Need to write a `riak_test` or two for pre-signed request processing, but that will also require some `erlcloud` hacking so going to punt on it for the time being.

**Comment by andrewjstone** [comment]
- [x] eunit & eqc tests
- [x] riak_test tests
- [x] dialyzer clean

+1 to merge

**Pull request closed without merging**
