### PR TITLE
403 instead of 404 returned when trying to list nonexistent bucket

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Adds a check when a valid user account attempts to list a bucket so that a `404` is returned if the bucket does not exist in the system. If the bucket does exist the system continues to return a `403`. Also adds a `check_bucket_exists` helper function to the `riak_cs_utils` module.

### CODE REVIEW

**Comment by slfritchie** [comment]
I'm a bit puzzled here.  If I have an environment where:
- Bucket 'test' is owned by the current user & is readable.
- Bucket 'test2' is owned by another user and has been set unreadable via `s3cmd setacl --acl-private s3://test2` by that other user
- Bucket 'testX' does not exist.

If I use the 'master' branch, I see:

```
% s3cmd --debug ls s3://test |& grep S3Error
% s3cmd --debug ls s3://test2 | & grep S3Error
DEBUG: S3Error: 403 (Forbidden)
% s3cmd --debug ls s3://testX | & grep S3Error
DEBUG: S3Error: 404 (Object Not Found)
```

If I use the 'cs296-nonexistent-bucket-404' branch, I see the exact same thing.

**Comment by kellymclaughlin** [comment]
I left out a key piece of information in the original problem description. This problem manifests when a bucket is created by a user and then subsequently deleted. Buckets that have never existed do not exhibit the problem.

**Comment by slfritchie** [comment]
+1 to the fix, -1 to the regression test (or, rather, lack of one).

Here's a rough sketch of what I'd done to create.

Setup:

```
s3cmd -c ~/.s3cfg.sbb-number1 mb s3://test
s3cmd -c ~/.s3cfg.sbb-number2 mb s3://test2
s3cmd -c ~/.s3cfg.sbb-number2 setacl --acl-private s3://test2
s3cmd -c ~/.s3cfg.sbb-number2 rb s3://test2
```

Master's behavior (bad):

```
% s3cmd -c ~/.s3cfg.sbb-number1 --debug ls s3://test |& grep S3Error
% s3cmd -c ~/.s3cfg.sbb-number1 --debug ls s3://test2 | & grep S3Error
DEBUG: S3Error: 403 (Forbidden)
% s3cmd -c ~/.s3cfg.sbb-number1 --debug ls s3://testX | & grep S3Error
DEBUG: S3Error: 404 (Object Not Found)
```

Whereas cs296-nonexistent-bucket-404's behavior yields 404 for both the 2nd & 3rd commands.

**Comment by reiddraper** [comment]
+1 to merge

**Pull request merged**
