### PR TITLE
Regroup JSON usage result

### PR DESCRIPTION
**Pull request by beerriot**
As detailed in [this gist](https://gist.github.com/b62a449ce4d97267e8e0), regroup the JSON response from /usage to separate samples from errors more clearly.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@kellymclaughlin can we add this to the 1.1 milestone?

**Comment by kellymclaughlin** [comment]
yeah, +1

**Comment by beerriot** [comment]
I believe I've made the requested changes, and did them for both JSON and XML, as an attempt at some consistency.

See also the changes to the doc on the wiki, on the `gh184-regroup-json` branch there.

**Comment by slfritchie** [comment]
+1 to merge, and no new Dialyzer warnings as a bonus

**Comment by cmeiklejohn** [comment]
+1

**Pull request merged**
