### PR TITLE
Add Riak Test shell script error handling

### PR DESCRIPTION
**Pull request by reiddraper**
Removes this fun issue:

```
cd /dir/does/not/exist
git reset --hard HEAD
```

### CODE REVIEW

**Comment by shino** [comment]
I think it's good to merge as is.

An alternative way of error handling which may be also good is
to use `trap` and `ERR`. It can tell where an error occurs.

Sample script (error_trap.sh):

```
#!/bin/bash

trap 'echo "[ERROR] $0:$LINENO \"$BASH_COMMAND\"" ; exit 1' ERR

ls no_such_file
echo "This line does not appear"
```

Output:

```
$ ./error_trap.sh
ls: cannot access no_such_file: No such file or directory
[ERROR] /home/shino/tmp/error_trap.sh:5 "ls no_such_file"
```

**Comment by shino** [comment]
Sorry. I pushed close button by mistake.

**Comment by reiddraper** [comment]
> An alternative way of error handling which may be also good is
> to use trap and ERR. It can tell where an error occurs.

Definitely. I'm going to go ahead and merge this in, but we can revisit this with better error handling later if it continues to be an issue. Any objections?

**Comment by shino** [comment]
No objection. I think your fix is sufficient :)
+1 to merge!

**Pull request merged**
