### PR TITLE
Corrected some typos.

### PR DESCRIPTION
**Pull request by GabrielNicolasAvellaneda**
Signed-off-by: GabrielNicolasAvellaneda avellaneda.gabriel@gmail.com

### CODE REVIEW

**Comment by shino** [comment]
@GabrielNicolasAvellaneda Good catch and thanks for contribution :smile:

**Comment by shino** [comment]
+1 efd23d5

**Comment by shino** [comment]
@borshop merge

**Comment by kuenishi** [comment]
RCS-278 (#1226)

**Pull request merged**
